/**
 * CLI launcher installation — VS Code-style "Install 'runbooks' command in PATH".
 *
 * Writes a small launcher that runs this copy of the app with the caller's
 * arguments, so the user can invoke `runbooks` from any terminal:
 *   macOS/Linux: /usr/local/bin/runbooks, a POSIX sh script
 *   Windows:     %LOCALAPPDATA%\Runbooks\bin\runbooks.cmd, with that directory
 *                added to the user's PATH
 *
 * The launcher is generated at install time and holds the app's absolute path.
 * A copy of a script inside the app loses the bundle-relative path it needs,
 * and on Linux an AppImage's resources live in a /tmp/.mount_* directory that
 * disappears when the app exits, so a link into it would dangle.
 *
 * /usr/local/bin is shared with every other tool on the machine, including the
 * older Go-based `runbooks` CLI. The launcher therefore carries a marker line,
 * and install and uninstall only replace or remove a file that has it.
 *
 * Everything that decides what to write, and whether a file is ours, is a pure
 * function or takes its paths as parameters so it can be tested without an
 * Electron app; the exported entry points read `app` / `process` and hand the
 * values over.
 */
import { app } from "electron"
import * as fs from "fs"
import * as os from "os"
import * as path from "path"
import { execFile as execFileCb } from "child_process"
import { promisify } from "util"

const execFile = promisify(execFileCb)

const UNIX_LAUNCHER_DIR = "/usr/local/bin"
const UNIX_LAUNCHER_PATH = path.posix.join(UNIX_LAUNCHER_DIR, "runbooks")
const WINDOWS_LAUNCHER_NAME = "runbooks.cmd"

/**
 * Identifies a launcher written by Runbooks.
 *
 * Changing this string orphans every launcher already installed: install would
 * refuse to replace them and uninstall would refuse to remove them.
 */
export const LAUNCHER_MARKER =
  "Generated by Runbooks (Install 'runbooks' command in PATH). Do not edit."

// A launcher is a few hundred bytes. Anything much larger (the Go CLI is tens
// of megabytes) is not ours, and is not worth reading to find that out.
const MAX_LAUNCHER_BYTES = 64 * 1024

// ---------------------------------------------------------------------------
// What the launcher runs
// ---------------------------------------------------------------------------

export interface LaunchTargetInput {
  platform: NodeJS.Platform
  /** `process.execPath`. */
  execPath: string
  /** `app.isPackaged`. */
  isPackaged: boolean
  /** Only APPIMAGE and APPDIR are read. */
  env: NodeJS.ProcessEnv
}

/**
 * The executable the launcher runs. Throws, with a message meant for the user,
 * when this copy of the app cannot be launched from a fixed path.
 */
export function resolveLaunchTarget(input: LaunchTargetInput): string {
  // In development execPath is the bare Electron binary, which on its own
  // opens Electron's default app rather than Runbooks.
  if (!input.isPackaged) {
    throw new Error(
      "The 'runbooks' command can only be installed from an installed copy of Runbooks, not a development build.",
    )
  }

  if (input.platform === "linux" && input.env.APPIMAGE) {
    // The AppImage runtime sets APPIMAGE to the .AppImage file and APPDIR to
    // its temporary mount. Both are inherited by child processes, so a .deb
    // install launched from inside another AppImage (a terminal, say) sees
    // that app's values; only trust them when we are running from that mount.
    const appDir = input.env.APPDIR
    if (!appDir || input.execPath.startsWith(appDir.endsWith("/") ? appDir : `${appDir}/`)) {
      return input.env.APPIMAGE
    }
  }

  if (input.platform === "darwin" && input.execPath.includes("/AppTranslocation/")) {
    // Gatekeeper runs a quarantined app opened in place (from Downloads or a
    // disk image) from a randomized read-only mount that goes away on quit.
    throw new Error(
      "Runbooks is running from a temporary location that macOS assigned it, so a 'runbooks' command pointing here would stop working when the app quits. Move Runbooks to your Applications folder, reopen it, and try again.",
    )
  }

  return input.execPath
}

// ---------------------------------------------------------------------------
// Launcher contents
// ---------------------------------------------------------------------------

/** Quote a string for a POSIX shell: wrap in single quotes, escape embedded ones. */
export function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`
}

/** The macOS/Linux launcher. `exec` so signals and the exit code pass straight through. */
export function renderUnixLauncher(target: string): string {
  return ["#!/bin/sh", `# ${LAUNCHER_MARKER}`, `exec ${shellSingleQuote(target)} "$@"`, ""].join("\n")
}

/**
 * The Windows launcher. cmd.exe expands `%VAR%` even inside double quotes, so a
 * literal `%` in the path is doubled; Windows paths cannot contain `"`. CRLF
 * line endings, because cmd.exe misparses LF-only batch files.
 *
 * cmd.exe also reads a batch file in the console's OEM code page rather than
 * UTF-8, so a non-ASCII user name in a per-user install path
 * (C:\Users\José\AppData\Local\Programs\...) would be misread. That prefix is
 * written as %LOCALAPPDATA% instead, which cmd.exe expands itself.
 */
export function renderWindowsLauncher(target: string, localAppData?: string): string {
  const base = localAppData?.replace(/\\+$/, "")
  const exe =
    base && target.toLowerCase().startsWith(`${base.toLowerCase()}\\`)
      ? `%LOCALAPPDATA%${target.slice(base.length).replace(/%/g, "%%")}`
      : target.replace(/%/g, "%%")
  return ["@echo off", `rem ${LAUNCHER_MARKER}`, `"${exe}" %*`, ""].join("\r\n")
}

// ---------------------------------------------------------------------------
// What is already at the launcher path
// ---------------------------------------------------------------------------

export interface LauncherProbe {
  /** False when nothing exists at the path. */
  present: boolean
  /**
   * The file's text, only when the path is a regular file small enough to be a
   * launcher. Undefined for symlinks (never followed), directories and binaries.
   */
  content?: string
}

export type LauncherState =
  /** Nothing at the launcher path. */
  | "absent"
  /** Our launcher, pointing at this copy of the app. */
  | "installed"
  /** Our launcher, written by a copy of the app that has since moved or changed. */
  | "stale"
  /** Something Runbooks did not write, such as the older Go CLI or another tool's symlink. */
  | "occupied"

export function probeLauncher(filePath: string): LauncherProbe {
  let stat: fs.Stats
  try {
    // lstat, not stat: a symlink is reported as present but never followed,
    // so a link into another tool's install can never be taken for ours.
    stat = fs.lstatSync(filePath)
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return { present: false }
    // Something is there that we cannot inspect; treat it as not ours.
    return { present: true }
  }
  if (!stat.isFile() || stat.size > MAX_LAUNCHER_BYTES) return { present: true }
  try {
    return { present: true, content: fs.readFileSync(filePath, "utf8") }
  } catch {
    return { present: true }
  }
}

export function isRunbooksLauncher(probe: LauncherProbe): boolean {
  return probe.content?.includes(LAUNCHER_MARKER) ?? false
}

export function classifyLauncher(probe: LauncherProbe, expected: string): LauncherState {
  if (!probe.present) return "absent"
  if (probe.content === expected) return "installed"
  return isRunbooksLauncher(probe) ? "stale" : "occupied"
}

// ---------------------------------------------------------------------------
// macOS / Linux: writing into /usr/local/bin
// ---------------------------------------------------------------------------

/**
 * Quote a string as an AppleScript literal.
 *
 * `do shell script "<cmd>"` puts the whole shell command inside an AppleScript
 * double-quoted string, so an unescaped backslash or double quote would end
 * the literal early in a command that runs with administrator privileges.
 */
export function appleScriptQuote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
}

/** Copy a staged launcher into place, creating the directory if needed. */
export function installCommand(staged: string, launcherPath: string): string {
  const dir = shellSingleQuote(path.posix.dirname(launcherPath))
  return `mkdir -p ${dir} && install -m 0755 ${shellSingleQuote(staged)} ${shellSingleQuote(launcherPath)}`
}

export function removeCommand(launcherPath: string): string {
  return `rm -f ${shellSingleQuote(launcherPath)}`
}

/**
 * How to run a shell command against the launcher directory: directly when
 * the user can already write there (Homebrew on Intel macOS owns
 * /usr/local/bin), otherwise through the platform's administrator prompt.
 */
export function shellInvocation(
  platform: NodeJS.Platform,
  command: string,
  writable: boolean,
): { file: string; args: string[] } {
  if (writable) return { file: "/bin/sh", args: ["-c", command] }
  if (platform === "darwin") {
    return {
      file: "osascript",
      args: ["-e", `do shell script ${appleScriptQuote(command)} with administrator privileges`],
    }
  }
  return { file: "pkexec", args: ["/bin/sh", "-c", command] }
}

export type ShellRunner = (command: string) => Promise<void>

/**
 * Write `content` to `launcherPath` unless something that is not ours is
 * already there. Guarded here rather than by callers: `cli:install` is an IPC
 * channel, and the welcome screen invokes it without checking status first.
 */
export async function installUnixLauncher(
  launcherPath: string,
  content: string,
  runShell: ShellRunner,
): Promise<void> {
  const state = classifyLauncher(probeLauncher(launcherPath), content)
  if (state === "installed") return
  if (state === "occupied") {
    throw new Error(
      `A different 'runbooks' command (possibly the older Runbooks CLI) already exists at ${launcherPath}, and Runbooks will not overwrite it. Remove or rename it, then try again.`,
    )
  }

  // Stage the file where an unprivileged process can write it, then let the
  // (possibly privileged) shell copy it into place. This keeps the launcher's
  // contents out of the command, which is nested inside AppleScript on macOS.
  const stagingDir = fs.mkdtempSync(path.join(os.tmpdir(), "runbooks-launcher-"))
  try {
    const staged = path.join(stagingDir, "runbooks")
    fs.writeFileSync(staged, content, { mode: 0o755 })
    await runShell(installCommand(staged, launcherPath))
  } finally {
    fs.rmSync(stagingDir, { recursive: true, force: true })
  }

  if (classifyLauncher(probeLauncher(launcherPath), content) !== "installed") {
    throw new Error(`Install reported success, but ${launcherPath} does not contain the Runbooks launcher.`)
  }
}

/**
 * Remove the launcher at `launcherPath` if Runbooks wrote it, including one
 * left by a copy of the app that has since moved. Resolves to false when
 * nothing is there, and refuses to touch anything else: `cli:uninstall` is an
 * IPC channel and must not delete another tool's `runbooks` as root.
 */
export async function uninstallUnixLauncher(
  launcherPath: string,
  runShell: ShellRunner,
): Promise<boolean> {
  const probe = probeLauncher(launcherPath)
  if (!probe.present) return false
  if (!isRunbooksLauncher(probe)) {
    throw new Error(
      `The 'runbooks' command at ${launcherPath} was not installed by Runbooks, so it was left in place.`,
    )
  }
  await runShell(removeCommand(launcherPath))
  return true
}

/** Can this user create, replace or remove an entry in `dir` without escalating? */
function isDirWritable(dir: string): boolean {
  try {
    fs.accessSync(dir, fs.constants.W_OK)
    return true
  } catch {
    // The directory may not exist yet, in which case the question is whether
    // we could create it, i.e. whether its parent is writable.
    if (fs.existsSync(dir)) return false
    try {
      fs.accessSync(path.dirname(dir), fs.constants.W_OK)
      return true
    } catch {
      return false
    }
  }
}

async function runLauncherDirShell(command: string): Promise<void> {
  const { file, args } = shellInvocation(process.platform, command, isDirWritable(UNIX_LAUNCHER_DIR))
  await execFile(file, args)
}

// ---------------------------------------------------------------------------
// Windows
// ---------------------------------------------------------------------------

/**
 * On Windows the launcher is written to a user-local directory and that
 * directory is added to the user's PATH.
 */
function getWindowsInstallDir(): string {
  const localAppData = process.env.LOCALAPPDATA || path.join(process.env.USERPROFILE || "", "AppData", "Local")
  return path.join(localAppData, "Runbooks", "bin")
}

// ---------------------------------------------------------------------------
// Check
// ---------------------------------------------------------------------------

function currentLaunchTarget(): string {
  return resolveLaunchTarget({
    platform: process.platform,
    execPath: process.execPath,
    isPackaged: app.isPackaged,
    env: process.env,
  })
}

function currentLauncherContent(target: string): string {
  return process.platform === "win32"
    ? renderWindowsLauncher(target, process.env.LOCALAPPDATA)
    : renderUnixLauncher(target)
}

function getLauncherPath(): string {
  return process.platform === "win32"
    ? path.join(getWindowsInstallDir(), WINDOWS_LAUNCHER_NAME)
    : UNIX_LAUNCHER_PATH
}

export interface CliInstallStatus {
  installed: boolean
  symlinkPath?: string
  targetPath?: string
  platform: string
}

export async function checkCliInstall(): Promise<CliInstallStatus> {
  const platform = process.platform
  const launcherPath = getLauncherPath()

  let target: string | undefined
  try {
    target = currentLaunchTarget()
  } catch {
    // A development or translocated build cannot install the command, so it
    // is never "installed" for it either; installCli reports why.
    return { installed: false, symlinkPath: launcherPath, platform }
  }

  // Only a launcher that runs this copy of the app counts. One left by a moved
  // app, or another tool's `runbooks`, reports not installed so that install
  // is offered (and repairs the former, or explains the latter).
  const state = classifyLauncher(probeLauncher(launcherPath), currentLauncherContent(target))
  return { installed: state === "installed", symlinkPath: launcherPath, targetPath: target, platform }
}

// ---------------------------------------------------------------------------
// Install
// ---------------------------------------------------------------------------

export async function installCli(): Promise<{ ok: true; symlinkPath: string }> {
  const target = currentLaunchTarget()

  if (process.platform === "win32") {
    return installWindows(target)
  }

  await installUnixLauncher(UNIX_LAUNCHER_PATH, currentLauncherContent(target), runLauncherDirShell)
  return { ok: true as const, symlinkPath: UNIX_LAUNCHER_PATH }
}

async function installWindows(target: string): Promise<{ ok: true; symlinkPath: string }> {
  const installDir = getWindowsInstallDir()
  const launcherPath = path.join(installDir, WINDOWS_LAUNCHER_NAME)

  // The directory belongs to Runbooks, so whatever is here is ours to replace,
  // including the copy of resources\bin\runbooks.cmd that older versions wrote
  // and that could not find the app from here.
  fs.mkdirSync(installDir, { recursive: true })
  fs.writeFileSync(launcherPath, currentLauncherContent(target), "utf8")

  // Add to user PATH if not already present
  await addToWindowsPath(installDir)

  return { ok: true as const, symlinkPath: launcherPath }
}

async function addToWindowsPath(dir: string): Promise<void> {
  // Read current user PATH from the registry
  const { stdout } = await execFile("reg", [
    "query",
    "HKCU\\Environment",
    "/v",
    "Path",
  ]).catch(() => ({ stdout: "" }))

  const match = stdout.match(/Path\s+REG_(?:EXPAND_)?SZ\s+(.*)/i)
  const currentPath = match ? match[1].trim() : ""

  // Check if already present (case-insensitive on Windows)
  const entries = currentPath.split(";").map((e) => e.toLowerCase())
  if (entries.includes(dir.toLowerCase())) {
    return
  }

  const newPath = currentPath ? `${currentPath};${dir}` : dir
  await execFile("reg", [
    "add",
    "HKCU\\Environment",
    "/v",
    "Path",
    "/t",
    "REG_EXPAND_SZ",
    "/d",
    newPath,
    "/f",
  ])

  // Broadcast WM_SETTINGCHANGE so running shells pick up the change
  try {
    await execFile("powershell", [
      "-NoProfile",
      "-Command",
      `Add-Type -Namespace Win32 -Name NativeMethods -MemberDefinition '[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)] public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);'; $HWND_BROADCAST = [IntPtr]0xffff; $WM_SETTINGCHANGE = 0x1a; $result = [UIntPtr]::Zero; [Win32.NativeMethods]::SendMessageTimeout($HWND_BROADCAST, $WM_SETTINGCHANGE, [UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$result)`,
    ])
  } catch {
    // Non-fatal — user can restart their shell
  }
}

// ---------------------------------------------------------------------------
// Uninstall
// ---------------------------------------------------------------------------

/** `removed` is false when there was no launcher to remove. */
export async function uninstallCli(): Promise<{ ok: true; removed: boolean }> {
  if (process.platform === "win32") {
    return uninstallWindows()
  }
  const removed = await uninstallUnixLauncher(UNIX_LAUNCHER_PATH, runLauncherDirShell)
  return { ok: true as const, removed }
}

async function uninstallWindows(): Promise<{ ok: true; removed: boolean }> {
  const installDir = getWindowsInstallDir()
  const launcherPath = path.join(installDir, WINDOWS_LAUNCHER_NAME)

  // Remove the launcher
  const removed = fs.existsSync(launcherPath)
  if (removed) {
    fs.unlinkSync(launcherPath)
  }

  // Remove from user PATH
  await removeFromWindowsPath(installDir)

  return { ok: true as const, removed }
}

async function removeFromWindowsPath(dir: string): Promise<void> {
  const { stdout } = await execFile("reg", [
    "query",
    "HKCU\\Environment",
    "/v",
    "Path",
  ]).catch(() => ({ stdout: "" }))

  const match = stdout.match(/Path\s+REG_(?:EXPAND_)?SZ\s+(.*)/i)
  if (!match) return

  const currentPath = match[1].trim()
  const entries = currentPath.split(";").filter(
    (e) => e.toLowerCase() !== dir.toLowerCase(),
  )
  const newPath = entries.join(";")
  // Uninstall runs even when nothing was installed; leave PATH untouched then.
  if (newPath === currentPath) return

  await execFile("reg", [
    "add",
    "HKCU\\Environment",
    "/v",
    "Path",
    "/t",
    "REG_EXPAND_SZ",
    "/d",
    newPath,
    "/f",
  ])
}
