version: '3'

tasks:
  build:
    desc: Build the complete binary with embedded frontend (set MIXPANEL_TOKEN env var to enable telemetry)
    deps: [build:frontend]
    cmds:
      - go build -ldflags="-X 'runbooks/api/telemetry.MixpanelToken={{.MIXPANEL_TOKEN}}'" -o runbooks .
    sources:
      - "**/*.go"
      - web/dist/**/*
    generates:
      - runbooks

  build:frontend:
    desc: Build the frontend (creates web/dist)
    dir: web
    env:
      VITE_MIXPANEL_TOKEN: "{{.MIXPANEL_TOKEN}}"
    cmds:
      - bun install
      - bun run build
    sources:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - package.json
    generates:
      - dist/**/*

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf web/dist
      - rm -f runbooks

  dev:frontend:
    desc: "Run the frontend dev server (Vite) - use with dev:backend in another terminal"
    dir: web
    cmds:
      - bun run dev

  dev:backend:
    desc: "Run the backend API server - usage: task dev:backend RUNBOOK_PATH=path/to/runbook"
    cmds:
      - go run . serve {{.RUNBOOK_PATH | default "testdata/my-first-runbook"}}

  test:
    desc: Run all tests (frontend and backend)
    cmds:
      - task: test:backend
      - task: test:frontend

  test:backend:
    desc: Run Go backend tests
    cmds:
      - go test ./...

  test:frontend:
    desc: Run frontend tests (vitest)
    dir: web
    cmds:
      - bun install
      - bun run test

  docs:linkcheck:
    desc: Check for broken links in documentation (builds first)
    dir: docs
    cmds:
      - bun install
      - bun run build
      - bun run linkcheck
