import { useIpc } from "./useIpc"
import type { UseIpcReturn } from "./useIpc"
import { useCallback, useEffect, startTransition } from "react"
import { useFileTreeUpdater } from "@/components/mdx/_shared/hooks/useFileTreeUpdater"
import type { FileTreeNode } from "@/components/artifacts/code/FileTree"
import type { HeavyDir } from "@/contexts/GeneratedFilesContext.types"

interface BoilerplateRenderResult {
  message: string
  outputDir: string
  templatePath: string
  /** Omitted when the render changed nothing (main's no-change shortcut). */
  fileTree?: FileTreeNode[]
  totalFiles?: number
  truncatedTree?: boolean
  heavyDirs?: HeavyDir[]
  deletedFiles?: string[]
  createdFiles?: string[]
  modifiedFiles?: string[]
  skippedFiles?: string[]
}

interface UseApiBoilerplateRenderResult extends UseIpcReturn<BoilerplateRenderResult> {
  /** Renders the template with these variables. Nothing renders until this is called. */
  render: (variables: Record<string, unknown>) => void
}

/**
 * Hook for rendering boilerplate templates via the API.
 *
 * @param templatePath - Path to the boilerplate template directory (required)
 * @param templateId - Unique ID of the Template component (required)
 * @param target - Where template output is written: "generated" (default) or "worktree"
 *
 * The backend uses templateId to track which files were generated by this template.
 * On re-render, it automatically cleans up orphaned files (e.g., when switching
 * from Python to Node.js runtime) and only writes files that have changed.
 */
export function useApiBoilerplateRender(
  templatePath: string,
  templateId: string,
  target?: "generated" | "worktree",
): UseApiBoilerplateRenderResult {
  const { applyFileTreeUpdate } = useFileTreeUpdater(target)

  // Lazy, because a render writes files and only the user's Generate click
  // may start one.
  const apiResult = useIpc<BoilerplateRenderResult>("boilerplate:render", undefined, {
    lazy: true,
    debounceMs: 0,
  })

  const { debouncedRequest } = apiResult
  const render = useCallback(
    (variables: Record<string, unknown>) => {
      if (debouncedRequest && templatePath && templateId) {
        debouncedRequest({
          templatePath,
          templateId,
          variables,
          ...(target ? { target } : {}),
        })
      }
    },
    [debouncedRequest, templatePath, templateId, target],
  )

  // Handle file tree updates when data changes.
  //
  // `applyFileTreeUpdate` bumps `treeVersion` in GitWorkTreeContext (and,
  // for non-worktree targets, also sets generated-files state). That
  // synchronously re-renders every consumer of those contexts — Workspace,
  // RepositoryFileBrowser, the changes panel, etc. — in the same React
  // commit as our render result. Measured paint cost: ~97ms after data
  // arrives, almost entirely due to this cascade.
  //
  // Wrapping in startTransition tells React the workspace refresh is
  // lower-priority than painting the template-render result. The Template
  // preview lands on next frame, the workspace catches up on the frame
  // after (or two) without blocking the visible result.
  const renderData = apiResult.data
  useEffect(() => {
    const fileTree = renderData?.fileTree
    if (renderData && Array.isArray(fileTree)) {
      startTransition(() => {
        applyFileTreeUpdate({ ...renderData, fileTree })
      })
    }
  }, [renderData, applyFileTreeUpdate])

  return {
    ...apiResult,
    render,
  }
}
