import { useApi } from './useApi';
import { useServiceCall } from './useServiceCall';
import type { UseApiReturn } from './useApi';
import { useMemo, useCallback, useEffect, useState, useRef } from 'react';
import { useFileTreeUpdater } from '@/components/mdx/_shared/hooks/useFileTreeUpdater';
import type { FileTreeNode } from '@/components/artifacts/code/FileTree';
import type { HeavyDir } from '@/contexts/GeneratedFilesContext.types';
import { isDesktop } from '@/lib/wails';
import { createAppError } from '@/types/error';
import * as BoilerplateService from '@/bindings/github.com/gruntwork-io/runbooks/services/boilerplateservice';
import { RenderRequest } from '@/bindings/github.com/gruntwork-io/runbooks/api/models';

interface BoilerplateRenderResult {
  message:      string,
  outputDir:    string,
  templatePath: string,
  fileTree:     FileTreeNode[],
  totalFiles?:  number,
  truncatedTree?: boolean,
  heavyDirs?: HeavyDir[],
  deletedFiles?:  string[],
  createdFiles?:  string[],
  modifiedFiles?: string[],
  skippedFiles?:  string[],
}

interface RenderRequestBody {
  templatePath: string;
  templateId: string;
  variables?: Record<string, unknown>;
  target?: 'generated' | 'worktree';
  [key: string]: unknown;
}

// Enhanced return type that includes auto-rendering functionality
interface UseApiBoilerplateRenderResult extends UseApiReturn<BoilerplateRenderResult> {
  isAutoRendering: boolean;
  autoRender: (templatePath: string, variables: Record<string, unknown>) => void;
}

/**
 * Hook for rendering boilerplate templates via the API.
 *
 * @param templatePath - Path to the boilerplate template directory (required)
 * @param templateId - Unique ID of the Template component (required)
 * @param variables - Variables to pass to the template
 * @param shouldFetch - Whether to fetch immediately (default: true)
 * @param target - Where template output is written: "generated" (default) or "worktree"
 *
 * The backend uses templateId to track which files were generated by this template.
 * On re-render, it automatically cleans up orphaned files (e.g., when switching
 * from Python to Node.js runtime) and only writes files that have changed.
 *
 * Desktop mode calls BoilerplateService.Render over IPC; browser mode hits
 * POST /api/boilerplate/render. The useApi hook supplies debounce/silent
 * refetch semantics; the IPC branch reproduces them with a local debounced
 * invoker so callers (<Template>, <Inputs>) see the same surface.
 */
export function useApiBoilerplateRender(
  templatePath: string,
  templateId: string,
  variables?: Record<string, unknown>,
  shouldFetch: boolean = true,
  target?: 'generated' | 'worktree'
): UseApiBoilerplateRenderResult {
  const { applyFileTreeUpdate } = useFileTreeUpdater(target);

  // Build the request body - both templatePath and templateId are required
  const requestBody = useMemo<RenderRequestBody | null>(() => {
    if (!shouldFetch) return null;
    if (templatePath && templateId) {
      return { templatePath, templateId, variables, ...(target ? { target } : {}) };
    }
    return null;
  }, [templatePath, templateId, variables, shouldFetch, target]);

  // --- Browser-mode HTTP path (unchanged) ---
  const httpResult = useApi<BoilerplateRenderResult>(
    !isDesktop() && shouldFetch ? '/api/boilerplate/render' : '', // Empty endpoint disables fetch
    'POST',
    requestBody || undefined,
    200 // 200ms debounce timeout
  );

  // --- Desktop IPC path ---
  // We piggy-back on useServiceCall for the initial render lifecycle
  // (data / isLoading / error) and layer a debounced invoker on top for
  // autoRender, which is what makes Template previews feel responsive.
  const ipcBaseResult = useServiceCall<BoilerplateRenderResult>(
    async () => {
      if (!requestBody) throw new Error('boilerplate render skipped');
      const req = RenderRequest.createFrom({
        templatePath: requestBody.templatePath,
        templateId: requestBody.templateId,
        variables: requestBody.variables ?? {},
        ...(requestBody.target ? { target: requestBody.target } : {}),
      });
      const res = await BoilerplateService.Render(req);
      if (!res) throw new Error('Render returned null');
      return res as unknown as BoilerplateRenderResult;
    },
    [requestBody],
    { lazy: !(isDesktop() && shouldFetch && requestBody !== null) },
  );

  // Local debounce for autoRender in desktop mode.
  const ipcData = ipcBaseResult.data;
  const ipcError = ipcBaseResult.error;
  const [ipcAutoData, setIpcAutoData] = useState<BoilerplateRenderResult | null>(null);
  const [ipcAutoLoading, setIpcAutoLoading] = useState(false);
  const [ipcAutoError, setIpcAutoError] = useState<string | null>(null);
  const debounceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Monotonic sequence for auto-render calls. Each runIpcRender captures
  // its seq at start; on completion it discards its result if a newer
  // seq has since been issued (either by a later run or by the base
  // result changing). Prevents a slow earlier call from clobbering a
  // faster later one, and prevents a stale auto-render from masking
  // a fresh base render.
  const renderSeqRef = useRef(0);

  const runIpcRender = useCallback(
    async (body: RenderRequestBody) => {
      const seq = ++renderSeqRef.current;
      setIpcAutoLoading(true);
      setIpcAutoError(null);
      try {
        const req = RenderRequest.createFrom({
          templatePath: body.templatePath,
          templateId: body.templateId,
          variables: body.variables ?? {},
          ...(body.target ? { target: body.target } : {}),
        });
        const res = await BoilerplateService.Render(req);
        if (seq !== renderSeqRef.current) return;
        if (!res) throw new Error('Render returned null');
        setIpcAutoData(res as unknown as BoilerplateRenderResult);
      } catch (err) {
        if (seq !== renderSeqRef.current) return;
        setIpcAutoError(err instanceof Error ? err.message : String(err));
      } finally {
        if (seq === renderSeqRef.current) {
          setIpcAutoLoading(false);
        }
      }
    },
    [],
  );

  const ipcDebouncedRequest = useCallback(
    (body: RenderRequestBody) => {
      if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current);
      debounceTimerRef.current = setTimeout(() => {
        void runIpcRender(body);
      }, 200);
    },
    [runIpcRender],
  );

  useEffect(() => {
    return () => {
      if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current);
    };
  }, []);

  // When the base render re-runs (requestBody deps changed) and produces
  // new data, invalidate any stale auto-render result so the merge below
  // doesn't keep returning the old one. Bumping renderSeqRef also
  // discards any in-flight auto-render that was started before the new
  // base data arrived.
  useEffect(() => {
    if (ipcData) {
      renderSeqRef.current++;
      setIpcAutoData(null);
    }
  }, [ipcData]);

  // Merge initial + auto results so callers see the most recent render.
  const ipcEffectiveData = ipcAutoData ?? ipcData ?? null;
  const ipcEffectiveLoading = ipcAutoLoading || ipcBaseResult.isLoading;
  const ipcEffectiveErrorMessage = ipcAutoError ?? (ipcError ? ipcError.message : null);

  // Choose the active result based on transport mode.
  const activeData = isDesktop() ? ipcEffectiveData : httpResult.data;
  const activeLoading = isDesktop() ? ipcEffectiveLoading : httpResult.isLoading;
  const activeErrorMessage = isDesktop() ? ipcEffectiveErrorMessage : (httpResult.error?.message ?? null);

  // Handle file tree updates when data changes
  useEffect(() => {
    if (activeData?.fileTree && Array.isArray(activeData.fileTree)) {
      applyFileTreeUpdate(activeData);
    }
  }, [activeData, applyFileTreeUpdate]);

  const autoRender = useCallback(
    (nextTemplatePath: string, nextVariables: Record<string, unknown>) => {
      if (!templateId || !nextTemplatePath) return;
      const body: RenderRequestBody = {
        templatePath: nextTemplatePath,
        templateId,
        variables: nextVariables,
        ...(target ? { target } : {}),
      };
      if (isDesktop()) {
        ipcDebouncedRequest(body);
        return;
      }
      if (httpResult.debouncedRequest) {
        httpResult.debouncedRequest(body);
      }
    },
    [templateId, target, httpResult, ipcDebouncedRequest],
  );

  if (isDesktop()) {
    return {
      data: activeData,
      isLoading: activeLoading,
      error: activeErrorMessage ? createAppError(activeErrorMessage) : null,
      refetch: ipcBaseResult.refetch,
      silentRefetch: ipcBaseResult.silentRefetch,
      debouncedRequest: (body: unknown) => ipcDebouncedRequest(body as RenderRequestBody),
      isAutoRendering: activeLoading,
      autoRender,
    };
  }

  return {
    ...httpResult,
    isAutoRendering: httpResult.isLoading,
    autoRender,
  };
}
