#!/usr/bin/env bash
set -e

# --- Runbooks Logging ---
if ! type log_info &>/dev/null; then
  source <(curl -fsSL https://raw.githubusercontent.com/gruntwork-io/runbooks/main/scripts/logging.sh 2>/dev/null) 2>/dev/null
  type log_info &>/dev/null || { log_info() { echo "[INFO]  $*"; }; log_warn() { echo "[WARN]  $*"; }; log_error() { echo "[ERROR] $*"; }; log_debug() { [ "${DEBUG:-}" = "true" ] && echo "[DEBUG] $*"; }; }
fi
# --- End Runbooks Logging ---

BRANCH_NAME="prototype-factory-setup"

if [ -z "$REPO_FILES" ]; then
    log_error "No cloned repo found. Please run the GitClone step first."
    exit 1
fi

log_info "Creating pull request from: ${REPO_FILES}"
log_info "  Branch: ${BRANCH_NAME}"

cd "$REPO_FILES"

# Create feature branch
if git ls-remote --heads origin "$BRANCH_NAME" 2>/dev/null | grep -q "$BRANCH_NAME"; then
    log_info "Branch '${BRANCH_NAME}' already exists, checking it out..."
    git fetch origin "$BRANCH_NAME"
    git checkout "$BRANCH_NAME"
else
    log_info "Creating new branch '${BRANCH_NAME}'..."
    git checkout -b "$BRANCH_NAME"
fi

# Check for changes
git add -A
if git diff --staged --quiet; then
    log_warn "No changes detected. Generated files may already exist in the repo."
    exit 0
fi

# Commit and push
log_info "Committing changes..."
git commit -m "Add prototype factory configuration

Adds CI/CD pipeline and infrastructure configuration generated
by the Prototype Factory runbook."

log_info "Pushing to GitHub..."
git push -u origin "$BRANCH_NAME" 2>&1

# Create or update PR
PR_EXISTS=$(gh pr list --head "$BRANCH_NAME" --json number --jq 'length' 2>/dev/null || echo "0")

if [ "$PR_EXISTS" -gt 0 ]; then
    PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')
    log_info "Pull request #${PR_NUMBER} updated with new commits!"
else
    log_info "Creating pull request..."
    gh pr create \
        --base main \
        --head "$BRANCH_NAME" \
        --title "Prototype Factory: infrastructure configuration" \
        --body "## Prototype Factory Setup

This PR was generated by the **Prototype Factory** runbook and adds:

- CI/CD pipeline (GitHub Actions)
- Lint, test, and deploy workflow
- Vercel preview + production deployment

### Architecture

\`\`\`
Channel (Next.js) → Orchestrator (FastAPI APIs) → Platform Services
\`\`\`

All services use clean contracts designed for swappable implementations."

    log_info "Pull request created!"
fi

echo ""
log_info "Done! Your pull request is ready for review."
