#!/usr/bin/env bash
set -e

# --- Runbooks Logging ---
if ! type log_info &>/dev/null; then
  source <(curl -fsSL https://raw.githubusercontent.com/gruntwork-io/runbooks/main/scripts/logging.sh 2>/dev/null) 2>/dev/null
  type log_info &>/dev/null || { log_info() { echo "[INFO]  $*"; }; log_warn() { echo "[WARN]  $*"; }; log_error() { echo "[ERROR] $*"; }; log_debug() { [ "${DEBUG:-}" = "true" ] && echo "[DEBUG] $*"; }; }
fi
# --- End Runbooks Logging ---

PROJECT_NAME="{{ .ProjectName }}"

if [ -z "$REPO_FILES" ]; then
    log_error "No cloned repo found. Please run the GitClone step first."
    exit 1
fi

log_info "Scaffolding Next.js frontend into: ${REPO_FILES}"
cd "$REPO_FILES"

# Create directory structure
mkdir -p src/app src/components src/lib src/styles public

# 1. package.json
cat > package.json << 'EOF'
{
  "name": "nextjs-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^15.1.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "@supabase/supabase-js": "^2.47.0",
    "@supabase/auth-helpers-nextjs": "^0.10.0"
  },
  "devDependencies": {
    "@types/node": "^22.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "typescript": "^5.7.0",
    "tailwindcss": "^4.0.0",
    "@tailwindcss/postcss": "^4.0.0",
    "postcss": "^8.5.0",
    "eslint": "^9.0.0",
    "eslint-config-next": "^15.1.0"
  }
}
EOF
log_info "Created package.json"

# 2. tsconfig.json
cat > tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF
log_info "Created tsconfig.json"

# 3. next.config.ts
cat > next.config.ts << 'EOF'
import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
EOF
log_info "Created next.config.ts"

# 4. postcss.config.mjs
cat > postcss.config.mjs << 'EOF'
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
EOF
log_info "Created postcss.config.mjs"

# 5. .gitignore
cat > .gitignore << 'EOF'
node_modules/
.next/
out/
build/
dist/
coverage/
*.pem
.DS_Store
npm-debug.log*
.env
.env*.local
.vercel
*.tsbuildinfo
next-env.d.ts
EOF
log_info "Created .gitignore"

# 6. .eslintrc.json
cat > .eslintrc.json << 'EOF'
{
  "extends": "next/core-web-vitals"
}
EOF
log_info "Created .eslintrc.json"

# 7. src/app/globals.css
cat > src/styles/globals.css << 'EOF'
@import "tailwindcss";
EOF
log_info "Created src/styles/globals.css"

# 8. src/app/layout.tsx
cat > src/app/layout.tsx << 'EOF'
import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by scaffold script",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
EOF
log_info "Created src/app/layout.tsx"

# 9. src/app/page.tsx
cat > src/app/page.tsx << 'EOF'
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to Next.js</h1>
      <p className="mt-4 text-lg text-gray-600">Get started by editing src/app/page.tsx</p>
    </main>
  );
}
EOF
log_info "Created src/app/page.tsx"

# 10. src/app/loading.tsx
cat > src/app/loading.tsx << 'EOF'
export default function Loading() {
  return <div className="flex min-h-screen items-center justify-center">Loading...</div>;
}
EOF
log_info "Created src/app/loading.tsx"

# 11. src/app/not-found.tsx
cat > src/app/not-found.tsx << 'EOF'
export default function NotFound() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <h2 className="text-2xl font-bold">Not Found</h2>
      <p className="mt-2">Could not find the requested resource.</p>
    </div>
  );
}
EOF
log_info "Created src/app/not-found.tsx"

# 12. src/app/error.tsx
cat > src/app/error.tsx << 'EOF'
"use client";

export default function Error({ error, reset }: { error: Error; reset: () => void }) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <h2 className="text-2xl font-bold">Something went wrong</h2>
      <button className="mt-4 rounded bg-blue-500 px-4 py-2 text-white" onClick={() => reset()}>
        Try again
      </button>
    </div>
  );
}
EOF
log_info "Created src/app/error.tsx"

# 13. src/lib/supabase.ts
cat > src/lib/supabase.ts << 'EOF'
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
EOF
log_info "Created src/lib/supabase.ts"

# 14. src/lib/utils.ts
cat > src/lib/utils.ts << 'EOF'
export function cn(...classes: (string | undefined | false)[]) {
  return classes.filter(Boolean).join(" ");
}
EOF
log_info "Created src/lib/utils.ts"

# 15. src/components/Header.tsx
cat > src/components/Header.tsx << 'EOF'
export default function Header() {
  return (
    <header className="border-b px-6 py-4">
      <nav className="flex items-center justify-between">
        <span className="text-xl font-semibold">Next.js App</span>
      </nav>
    </header>
  );
}
EOF
log_info "Created src/components/Header.tsx"

# 16. src/components/Footer.tsx
cat > src/components/Footer.tsx << 'EOF'
export default function Footer() {
  return (
    <footer className="border-t px-6 py-4 text-center text-sm text-gray-500">
      &copy; {new Date().getFullYear()} Next.js App
    </footer>
  );
}
EOF
log_info "Created src/components/Footer.tsx"

# 17. public/favicon.ico (empty placeholder)
touch public/favicon.ico
log_info "Created public/favicon.ico"

# 18. .env.example
cat > .env.example << 'EOF'
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
EOF
log_info "Created .env.example"

# 19. README.md
cat > README.md << 'EOF'
# Next.js App

Scaffolded with TypeScript, Tailwind CSS, and Supabase Auth.

## Getting Started

```bash
npm install
npm run dev
```

Open [http://localhost:3000](http://localhost:3000) in your browser.
EOF
log_info "Created README.md"

# 20. next-env.d.ts
cat > next-env.d.ts << 'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />
EOF
log_info "Created next-env.d.ts"

# Install dependencies
log_info "Installing dependencies..."
npm install 2>&1

# Commit and push
log_info "Committing and pushing..."
git add -A
git commit -m "Initial Next.js scaffold with TypeScript, Tailwind CSS, and Supabase Auth"
git push -u origin main 2>&1

echo ""
log_info "=== Frontend Scaffold ==="
log_info "  Framework:     Next.js (latest) + React 19"
log_info "  Styling:       Tailwind CSS"
log_info "  Language:      TypeScript"
log_info "  Auth:          Supabase Auth Helpers (installed)"
log_info "  Files created: 20"
