// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BoilerplateConfig represents the parsed boilerplate.yml, which is a collection of variables
 */
export class BoilerplateConfig {
    "variables": BoilerplateVariable[];

    /**
     * Sections is an ordered list of section groupings for UI rendering.
     * Each Section contains a name and the list of variable names in that section.
     * Note: Individual variables also have a SectionName field for direct lookup.
     */
    "sections"?: Section[];

    /**
     * OutputDependencies lists references to other blocks' outputs found in template files.
     * These are {{ .outputs.blockId.outputName }} patterns that must be satisfied
     * before the template can be rendered. The Template component uses this to show warnings
     * when dependent blocks haven't been executed yet.
     */
    "outputDependencies"?: OutputDependency[];

    /** Creates a new BoilerplateConfig instance. */
    constructor($$source: Partial<BoilerplateConfig> = {}) {
        if (!("variables" in $$source)) {
            this["variables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoilerplateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BoilerplateConfig {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField0_0($$parsedSource["variables"]);
        }
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField1_0($$parsedSource["sections"]);
        }
        if ("outputDependencies" in $$parsedSource) {
            $$parsedSource["outputDependencies"] = $$createField2_0($$parsedSource["outputDependencies"]);
        }
        return new BoilerplateConfig($$parsedSource as Partial<BoilerplateConfig>);
    }
}

/**
 * BoilerplateRequest represents the request body for boilerplate variable parsing
 */
export class BoilerplateRequest {
    /**
     * Path to the boilerplate template directory
     */
    "templatePath"?: string;

    /**
     * Direct content of the boilerplate.yml file
     */
    "boilerplateContent"?: string;

    /** Creates a new BoilerplateRequest instance. */
    constructor($$source: Partial<BoilerplateRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoilerplateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BoilerplateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BoilerplateRequest($$parsedSource as Partial<BoilerplateRequest>);
    }
}

/**
 * BoilerplateValidationType represents the supported validation types from boilerplate
 * The list of supported validations is current as of Sep 2025.
 * https://github.com/gruntwork-io/boilerplate?tab=readme-ov-file#validations
 */
export enum BoilerplateValidationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ValidationRequired = "required",
    ValidationURL = "url",
    ValidationEmail = "email",
    ValidationAlpha = "alpha",
    ValidationDigit = "digit",
    ValidationAlphanumeric = "alphanumeric",
    ValidationCountryCode2 = "countrycode2",
    ValidationSemver = "semver",
    ValidationLength = "length",
    ValidationRegex = "regex",
    ValidationCustom = "custom",
};

/**
 * BoilerplateVarType represents the supported variable types from boilerplate.
 * These map to the boilerplate package's BoilerplateType values.
 */
export enum BoilerplateVarType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VarTypeString = "string",
    VarTypeInt = "int",
    VarTypeFloat = "float",
    VarTypeBool = "bool",
    VarTypeList = "list",
    VarTypeMap = "map",
    VarTypeEnum = "enum",
};

/**
 * BoilerplateVariable represents a variable definition from boilerplate.yml
 * Note that we define a simplified version of the BoilerplateVariable struct here.
 * The official Variable struct in the boilerplate package is more complex and includes additional fields we don't need.
 */
export class BoilerplateVariable {
    "name": string;
    "description": string;
    "type": BoilerplateVarType;
    "default": any;
    "required": boolean;
    "options"?: string[];
    "validations"?: ValidationRule[];
    "sensitive"?: boolean;

    /**
     * Schema is a field not known to boilerplate itself, but we use it to allow users to define a schema for structured maps.
     * For example, a user could specify a schema for an AWS account map with the fields "email", "environment", and "id".
     * The frontend will then use this schema to render a form for the user to enter the data.
     * It will send the data to boilerplate as a map of strings, where the key is the entry name and the value is a map of strings,
     * where the key is the field name and the value is the field value.
     * YAML property: x-schema (Gruntbooks extension, ignored by Boilerplate)
     * For structured maps: field name -> type mapping
     */
    "schema"?: { [_ in string]?: string };

    /**
     * SchemaInstanceLabel is a field not known to boilerplate itself, but we use it to allow users to name an instance of a schema.
     * For example, a user could specify a schema instance label for an AWS account map with the value "Account Name".
     * The frontend will then use this label to render a form for the user to enter the data.
     * It will send the data to boilerplate as a map of strings, where the key is the entry name and the value is a map of strings,
     * where the key is the field name and the value is the field value.
     * YAML property: x-schema-instance-label (Gruntbooks extension, ignored by Boilerplate)
     * Custom label for schema instances (e.g., "Account Name")
     */
    "schemaInstanceLabel"?: string;

    /**
     * SectionName indicates which section this variable belongs to.
     * Used to look up a variable's section without searching the top-level Sections list.
     * See also: BoilerplateConfig.Sections for the ordered list of all section groupings.
     * YAML property: x-section (Gruntbooks extension, ignored by Boilerplate)
     */
    "sectionName"?: string;

    /** Creates a new BoilerplateVariable instance. */
    constructor($$source: Partial<BoilerplateVariable> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = BoilerplateVarType.$zero;
        }
        if (!("default" in $$source)) {
            this["default"] = null;
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BoilerplateVariable instance from a string or object.
     */
    static createFrom($$source: any = {}): BoilerplateVariable {
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        const $$createField8_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        if ("validations" in $$parsedSource) {
            $$parsedSource["validations"] = $$createField6_0($$parsedSource["validations"]);
        }
        if ("schema" in $$parsedSource) {
            $$parsedSource["schema"] = $$createField8_0($$parsedSource["schema"]);
        }
        return new BoilerplateVariable($$parsedSource as Partial<BoilerplateVariable>);
    }
}

/**
 * GeneratedFilesCheckResponse represents the response from the generated files check endpoint
 */
export class GeneratedFilesCheckResponse {
    /**
     * Whether files exist in the output directory
     */
    "hasFiles": boolean;

    /**
     * Absolute output path that was checked
     */
    "absoluteOutputPath": string;

    /**
     * The CLI-configured output path (as provided to --output-path)
     */
    "relativeOutputPath": string;

    /**
     * Number of files found (0 if directory doesn't exist)
     */
    "fileCount": number;

    /** Creates a new GeneratedFilesCheckResponse instance. */
    constructor($$source: Partial<GeneratedFilesCheckResponse> = {}) {
        if (!("hasFiles" in $$source)) {
            this["hasFiles"] = false;
        }
        if (!("absoluteOutputPath" in $$source)) {
            this["absoluteOutputPath"] = "";
        }
        if (!("relativeOutputPath" in $$source)) {
            this["relativeOutputPath"] = "";
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratedFilesCheckResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneratedFilesCheckResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneratedFilesCheckResponse($$parsedSource as Partial<GeneratedFilesCheckResponse>);
    }
}

/**
 * GeneratedFilesDeleteResponse represents the response from the generated files delete endpoint
 */
export class GeneratedFilesDeleteResponse {
    /**
     * Whether the deletion was successful
     */
    "success": boolean;

    /**
     * Number of files/folders deleted
     */
    "deletedCount": number;

    /**
     * Human-readable message about the operation
     */
    "message": string;

    /** Creates a new GeneratedFilesDeleteResponse instance. */
    constructor($$source: Partial<GeneratedFilesDeleteResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("deletedCount" in $$source)) {
            this["deletedCount"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratedFilesDeleteResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneratedFilesDeleteResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneratedFilesDeleteResponse($$parsedSource as Partial<GeneratedFilesDeleteResponse>);
    }
}

/**
 * OutputDependency represents a reference to another block's output in a template.
 * These are found by scanning template files for {{ .outputs.blockId.outputName }} patterns.
 */
export class OutputDependency {
    /**
     * The block ID that produces the output (e.g., "create-account")
     */
    "blockId": string;

    /**
     * The output name (e.g., "account_id")
     */
    "outputName": string;

    /**
     * The full template reference (e.g., "outputs.create_account.account_id")
     */
    "fullPath": string;

    /** Creates a new OutputDependency instance. */
    constructor($$source: Partial<OutputDependency> = {}) {
        if (!("blockId" in $$source)) {
            this["blockId"] = "";
        }
        if (!("outputName" in $$source)) {
            this["outputName"] = "";
        }
        if (!("fullPath" in $$source)) {
            this["fullPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputDependency instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputDependency {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputDependency($$parsedSource as Partial<OutputDependency>);
    }
}

/**
 * Section represents a grouping of variables under a section header (Gruntbooks extension).
 * This is used for UI rendering (e.g., rendering groups of variables in sections in the form).
 * See also: BoilerplateVariable.SectionName for per-variable section lookup.
 * YAML property: x-section (Gruntbooks extension, ignored by Boilerplate)
 */
export class Section {
    /**
     * Section name ("" for unnamed/default section)
     */
    "name": string;

    /**
     * Variable names in this section (in declaration order)
     */
    "variables": string[];

    /** Creates a new Section instance. */
    constructor($$source: Partial<Section> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("variables" in $$source)) {
            this["variables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Section instance from a string or object.
     */
    static createFrom($$source: any = {}): Section {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField1_0($$parsedSource["variables"]);
        }
        return new Section($$parsedSource as Partial<Section>);
    }
}

/**
 * TfModuleMetadata holds additional metadata extracted from a TF module directory.
 */
export class TfModuleMetadata {
    /**
     * Name of the containing directory
     */
    "folder_name": string;

    /**
     * First h1 heading from README.md, if present
     */
    "readme_title": string;

    /**
     * Names of output blocks
     */
    "output_names": string[];

    /**
     * Names of resource blocks (excluding data sources)
     */
    "resource_names": string[];

    /** Creates a new TfModuleMetadata instance. */
    constructor($$source: Partial<TfModuleMetadata> = {}) {
        if (!("folder_name" in $$source)) {
            this["folder_name"] = "";
        }
        if (!("readme_title" in $$source)) {
            this["readme_title"] = "";
        }
        if (!("output_names" in $$source)) {
            this["output_names"] = [];
        }
        if (!("resource_names" in $$source)) {
            this["resource_names"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TfModuleMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): TfModuleMetadata {
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("output_names" in $$parsedSource) {
            $$parsedSource["output_names"] = $$createField2_0($$parsedSource["output_names"]);
        }
        if ("resource_names" in $$parsedSource) {
            $$parsedSource["resource_names"] = $$createField3_0($$parsedSource["resource_names"]);
        }
        return new TfModuleMetadata($$parsedSource as Partial<TfModuleMetadata>);
    }
}

/**
 * TfParseRequest is the request body for POST /api/tf/parse.
 */
export class TfParseRequest {
    /**
     * Source can be a local relative path (e.g., "../modules/vpc") or a remote URL
     * in any format supported by ParseRemoteSource (GitHub shorthand, git:: prefix,
     * GitHub/GitLab browser URLs).
     */
    "source": string;

    /** Creates a new TfParseRequest instance. */
    constructor($$source: Partial<TfParseRequest> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TfParseRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TfParseRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TfParseRequest($$parsedSource as Partial<TfParseRequest>);
    }
}

/**
 * TfParseResponse extends BoilerplateConfig with module-level metadata.
 * The variables, sections, and outputDependencies fields come from BoilerplateConfig.
 * The module metadata fields are additional.
 */
export class TfParseResponse {
    "variables": BoilerplateVariable[];

    /**
     * Sections is an ordered list of section groupings for UI rendering.
     * Each Section contains a name and the list of variable names in that section.
     * Note: Individual variables also have a SectionName field for direct lookup.
     */
    "sections"?: Section[];

    /**
     * OutputDependencies lists references to other blocks' outputs found in template files.
     * These are {{ .outputs.blockId.outputName }} patterns that must be satisfied
     * before the template can be rendered. The Template component uses this to show warnings
     * when dependent blocks haven't been executed yet.
     */
    "outputDependencies"?: OutputDependency[];
    "metadata": TfModuleMetadata;

    /** Creates a new TfParseResponse instance. */
    constructor($$source: Partial<TfParseResponse> = {}) {
        if (!("variables" in $$source)) {
            this["variables"] = [];
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = (new TfModuleMetadata());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TfParseResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TfParseResponse {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField0_0($$parsedSource["variables"]);
        }
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField1_0($$parsedSource["sections"]);
        }
        if ("outputDependencies" in $$parsedSource) {
            $$parsedSource["outputDependencies"] = $$createField2_0($$parsedSource["outputDependencies"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField3_0($$parsedSource["metadata"]);
        }
        return new TfParseResponse($$parsedSource as Partial<TfParseResponse>);
    }
}

/**
 * ValidationRule represents a validation rule from a boilerplate.yml.
 */
export class ValidationRule {
    "type": BoilerplateValidationType;
    "message": string;
    "args"?: any[];

    /** Creates a new ValidationRule instance. */
    constructor($$source: Partial<ValidationRule> = {}) {
        if (!("type" in $$source)) {
            this["type"] = BoilerplateValidationType.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationRule instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationRule {
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        return new ValidationRule($$parsedSource as Partial<ValidationRule>);
    }
}

/**
 * WorkspaceChangesResponse is the response for GET /api/workspace/changes.
 */
export class WorkspaceChangesResponse {
    "changes": WorkspaceFileChange[];
    "totalChanges": number;
    "tooManyChanges"?: boolean;

    /** Creates a new WorkspaceChangesResponse instance. */
    constructor($$source: Partial<WorkspaceChangesResponse> = {}) {
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("totalChanges" in $$source)) {
            this["totalChanges"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceChangesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceChangesResponse {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField0_0($$parsedSource["changes"]);
        }
        return new WorkspaceChangesResponse($$parsedSource as Partial<WorkspaceChangesResponse>);
    }
}

/**
 * WorkspaceFileChange represents a single file change in a git workspace.
 */
export class WorkspaceFileChange {
    "path": string;

    /**
     * "added", "modified", "deleted"
     */
    "changeType": string;
    "additions": number;
    "deletions": number;
    "originalContent"?: string;
    "newContent"?: string;
    "language": string;
    "isBinary"?: boolean;
    "diffTruncated"?: boolean;

    /** Creates a new WorkspaceFileChange instance. */
    constructor($$source: Partial<WorkspaceFileChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("changeType" in $$source)) {
            this["changeType"] = "";
        }
        if (!("additions" in $$source)) {
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            this["deletions"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceFileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceFileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceFileChange($$parsedSource as Partial<WorkspaceFileChange>);
    }
}

/**
 * WorkspaceFileResponse is the response for GET /api/workspace/file.
 */
export class WorkspaceFileResponse {
    "path": string;
    "content"?: string;
    "language": string;
    "size": number;
    "isImage"?: boolean;
    "mimeType"?: string;
    "dataUri"?: string;
    "isBinary"?: boolean;
    "isTooLarge"?: boolean;

    /** Creates a new WorkspaceFileResponse instance. */
    constructor($$source: Partial<WorkspaceFileResponse> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceFileResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceFileResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceFileResponse($$parsedSource as Partial<WorkspaceFileResponse>);
    }
}

/**
 * WorkspaceGitInfo contains git metadata for a workspace.
 */
export class WorkspaceGitInfo {
    "ref": string;

    /**
     * "branch", "tag", or "commit"
     */
    "refType": string;
    "remoteUrl": string;
    "commitSha": string;

    /** Creates a new WorkspaceGitInfo instance. */
    constructor($$source: Partial<WorkspaceGitInfo> = {}) {
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }
        if (!("refType" in $$source)) {
            this["refType"] = "";
        }
        if (!("remoteUrl" in $$source)) {
            this["remoteUrl"] = "";
        }
        if (!("commitSha" in $$source)) {
            this["commitSha"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceGitInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceGitInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceGitInfo($$parsedSource as Partial<WorkspaceGitInfo>);
    }
}

/**
 * WorkspaceTreeNode represents a file or folder in the workspace tree (structure only, no content).
 */
export class WorkspaceTreeNode {
    /**
     * ID is the unique identifier for this node, typically the file path relative to the workspace root.
     */
    "id": string;

    /**
     * Name is the display name of the file or folder (e.g., "main.go", "src").
     */
    "name": string;

    /**
     * Type is either "file" or "folder".
     */
    "type": string;

    /**
     * Size is the file size in bytes. Only set for files, omitted for folders.
     */
    "size"?: number;

    /**
     * Language is the detected programming language of the file (e.g., "go", "typescript").
     */
    "language"?: string;

    /**
     * IsBinary is true when the file is detected as a binary (non-text) file.
     */
    "isBinary"?: boolean;

    /**
     * IsIgnored is true when the file or folder is matched by .gitignore rules.
     * The frontend renders these with muted styling to indicate they are not tracked by git.
     */
    "isIgnored"?: boolean;

    /**
     * IsLazyLoad is true for folders that contain too many entries to load upfront (>500 children).
     * The frontend shows a placeholder and fetches the subtree on demand when the user expands the folder.
     */
    "isLazyLoad"?: boolean;

    /**
     * Children contains the nested files and folders within this folder. Empty for files.
     */
    "children"?: WorkspaceTreeNode[];

    /** Creates a new WorkspaceTreeNode instance. */
    constructor($$source: Partial<WorkspaceTreeNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeNode {
        const $$createField8_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField8_0($$parsedSource["children"]);
        }
        return new WorkspaceTreeNode($$parsedSource as Partial<WorkspaceTreeNode>);
    }
}

/**
 * WorkspaceTreeResponse is the response for GET /api/workspace/tree.
 */
export class WorkspaceTreeResponse {
    "tree": WorkspaceTreeNode[];
    "totalFiles": number;
    "gitInfo"?: WorkspaceGitInfo | null;

    /** Creates a new WorkspaceTreeResponse instance. */
    constructor($$source: Partial<WorkspaceTreeResponse> = {}) {
        if (!("tree" in $$source)) {
            this["tree"] = [];
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeResponse {
        const $$createField0_0 = $$createType15;
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tree" in $$parsedSource) {
            $$parsedSource["tree"] = $$createField0_0($$parsedSource["tree"]);
        }
        if ("gitInfo" in $$parsedSource) {
            $$parsedSource["gitInfo"] = $$createField2_0($$parsedSource["gitInfo"]);
        }
        return new WorkspaceTreeResponse($$parsedSource as Partial<WorkspaceTreeResponse>);
    }
}

// Private type creation functions
const $$createType0 = BoilerplateVariable.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Section.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = OutputDependency.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = ValidationRule.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = TfModuleMetadata.createFrom;
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = WorkspaceFileChange.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = WorkspaceTreeNode.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = WorkspaceGitInfo.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
