#!/bin/bash
# Generate a deployment configuration file.
# Files written to $GENERATED_FILES are captured and appear in the Generated tab.

set -euo pipefail

# Support both new and legacy env var names
FILES_DIR="${GENERATED_FILES:-${RUNBOOK_FILES:-}}"

if [ -z "$FILES_DIR" ]; then
    echo "Error: GENERATED_FILES is not set."
    echo "This variable is automatically provided by the Runbooks server."
    exit 1
fi

echo "Generating deployment configuration..."
echo ""

cat > "$FILES_DIR/deploy-config.yaml" << 'EOF'
# Deployment Configuration
# Generated by Runbooks

environment: non-prod
region: us-east-1
stack: stateful-ec2-asg-service

settings:
  auto_approve: false
  parallelism: 10
  refresh: true

tags:
  managed_by: runbooks
  team: platform-engineering
EOF

echo "Created deploy-config.yaml in $FILES_DIR"
echo ""
echo "This file will appear in the Generated tab."
