/**
 * File manifest tracking.
 *
 * Tracks files generated by template blocks to enable smart cleanup. When a
 * template re-renders with different variables, the manifest detects which
 * files are orphaned and should be deleted automatically.
 *
 * Implements "block-scoped file manifests" where each Template component
 * (identified by its ID) owns a specific set of generated files. On re-render
 * only files that are no longer produced are deleted, and only changed files
 * are rewritten.
 */

import path from "node:path"
import { Effect, Stream } from "effect"
import crypto from "node:crypto"

import { FileSystem } from "../../services/FileSystem.js"
import { isContainedIn, isFilesystemRoot } from "../../path-validation.js"
import type {
  ManifestEntry,
  TemplateManifest,
  ManifestDiffResult,
} from "../../types.js"

// ---------------------------------------------------------------------------
// Hashing
// ---------------------------------------------------------------------------

/** Compute a SHA-256 hex digest of file content. */
export function hashFileContent(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex")
}

// ---------------------------------------------------------------------------
// FileManifestStore — in-memory store mapping templateId -> TemplateManifest
// ---------------------------------------------------------------------------

export class FileManifestStore {
  private manifests = new Map<string, TemplateManifest>()

  /** Retrieve the manifest for a template ID, or undefined if absent. */
  get(templateId: string): TemplateManifest | undefined {
    return this.manifests.get(templateId)
  }

  /** Store a manifest for a template ID. */
  set(templateId: string, manifest: TemplateManifest): void {
    this.manifests.set(templateId, manifest)
  }

  /** Remove a manifest for a template ID. */
  delete(templateId: string): void {
    this.manifests.delete(templateId)
  }

  /** Remove all manifests (useful for testing). */
  clear(): void {
    this.manifests.clear()
  }
}

// ---------------------------------------------------------------------------
// Global singleton
// ---------------------------------------------------------------------------

const globalManifestStore = new FileManifestStore()

/** Return the global manifest store instance. */
export function getManifestStore(): FileManifestStore {
  return globalManifestStore
}

// ---------------------------------------------------------------------------
// Build manifest from directory
// ---------------------------------------------------------------------------

/**
 * Scan a directory recursively and build a manifest of all files with their
 * SHA-256 content hashes.
 *
 * Returns an Effect that requires the FileSystem service.
 */
export function buildManifestFromDirectory(rootDir: string) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem

    const entries: ManifestEntry[] = []

    // Collect walk entries into an array
    const walkEntries = yield* Stream.runCollect(fs.walk(rootDir))

    for (const entry of walkEntries) {
      if (!entry.isFile) continue

      const content = yield* fs.readFile(entry.path)
      entries.push({
        path: entry.relativePath,
        contentHash: hashFileContent(content),
      })
    }

    return entries
  })
}

// ---------------------------------------------------------------------------
// Diff computation
// ---------------------------------------------------------------------------

/**
 * Compare old and new manifest entries to determine what actions are needed.
 *
 * Returns which files are orphaned (in old but not new), created (in new but
 * not old), modified (in both but different hash), or unchanged.
 */
export function computeDiff(
  oldEntries: ManifestEntry[],
  newEntries: ManifestEntry[],
): ManifestDiffResult {
  const oldMap = new Map<string, string>()
  for (const e of oldEntries) {
    oldMap.set(e.path, e.contentHash)
  }

  const newMap = new Map<string, string>()
  for (const e of newEntries) {
    newMap.set(e.path, e.contentHash)
  }

  const orphaned: string[] = []
  const created: string[] = []
  const modified: string[] = []
  const unchanged: string[] = []

  // Files in old but not in new — orphaned
  for (const path of oldMap.keys()) {
    if (!newMap.has(path)) {
      orphaned.push(path)
    }
  }

  // Categorise new files
  for (const [path, newHash] of newMap) {
    const oldHash = oldMap.get(path)
    if (oldHash === undefined) {
      created.push(path)
    } else if (oldHash === newHash) {
      unchanged.push(path)
    } else {
      modified.push(path)
    }
  }

  return { orphaned, created, modified, unchanged }
}

// ---------------------------------------------------------------------------
// Apply diff — patch the real output directory from a rendered source tree
// ---------------------------------------------------------------------------

/**
 * Result of applying a diff.
 */
export interface ApplyDiffResult {
  readonly written: number
  readonly deleted: number
}

/**
 * Copy a single file from sourceDir to outputDir, preserving the relative path
 * and creating parent directories as needed.
 */
function copyFileForManifest(
  sourceDir: string,
  outputDir: string,
  relPath: string,
) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem
    const srcPath = path.join(sourceDir, relPath)
    const dstPath = path.join(outputDir, relPath)

    // Use buffer read/write so binary files round-trip intact.
    const content = yield* fs.readFileBuffer(srcPath)
    yield* fs.mkdir(path.dirname(dstPath), { recursive: true })
    yield* fs.writeFile(dstPath, content)
  })
}

/**
 * Walk up from `dir` removing empty directories, stopping at `stopAt`.
 * Never removes `stopAt` itself, anything outside `stopAt`, or a filesystem
 * root. Silently ignores removal failures (non-empty, permission, etc.).
 */
function cleanupEmptyParentDirs(dir: string, stopAt: string) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem
    let current = dir
    while (current !== stopAt && current !== "." && !isFilesystemRoot(current)) {
      if (!isContainedIn(current, stopAt)) return
      const entries = yield* fs.readdir(current).pipe(Effect.either)
      if (entries._tag === "Left" || entries.right.length > 0) return
      const removed = yield* fs.rm(current, { recursive: false }).pipe(Effect.either)
      if (removed._tag === "Left") return
      current = path.dirname(current)
    }
  })
}

/**
 * Apply a manifest diff by patching `outputDir` to match `sourceDir`:
 *  - delete orphaned files (present in the prior manifest but not the new one)
 *  - copy created and modified files from `sourceDir` to `outputDir`
 *  - leave unchanged files alone, but recreate them if the user manually
 *    deleted them between renders
 *
 * Orphan scope is manifest-based, so files in `outputDir` that this template
 * never produced are never touched — safe to run against a shared worktree.
 */
export function applyDiff(
  diff: ManifestDiffResult,
  sourceDir: string,
  outputDir: string,
) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem
    let written = 0
    let deleted = 0

    // Delete orphans and clean up any newly-empty parent directories.
    for (const relPath of diff.orphaned) {
      const fullPath = path.join(outputDir, relPath)
      const result = yield* fs.rm(fullPath, { force: true }).pipe(Effect.either)
      if (result._tag === "Right") deleted++
      yield* cleanupEmptyParentDirs(path.dirname(fullPath), outputDir)
    }

    // Write created files.
    for (const relPath of diff.created) {
      yield* copyFileForManifest(sourceDir, outputDir, relPath)
      written++
    }

    // Write modified files.
    for (const relPath of diff.modified) {
      yield* copyFileForManifest(sourceDir, outputDir, relPath)
      written++
    }

    // Unchanged files: skip unless the user manually deleted them on disk.
    for (const relPath of diff.unchanged) {
      const fullPath = path.join(outputDir, relPath)
      const exists = yield* fs.exists(fullPath)
      if (!exists) {
        yield* copyFileForManifest(sourceDir, outputDir, relPath)
        written++
      }
    }

    return { written, deleted } satisfies ApplyDiffResult
  })
}
