/**
 * File manifest tracking.
 *
 * Tracks files generated by template blocks to enable smart cleanup. When a
 * template re-renders with different variables, the manifest detects which
 * files are orphaned and should be deleted automatically.
 *
 * Implements "block-scoped file manifests" where each Template component
 * (identified by its ID) owns a specific set of generated files. On re-render
 * only files that are no longer produced are deleted, and only changed files
 * are rewritten.
 */

import path from "node:path"
import { Chunk, Effect, Stream } from "effect"
import crypto from "node:crypto"

import { FileSystem } from "../../services/FileSystem.js"
import {
  containsPathTraversal,
  isAbsolutePath,
  isContainedIn,
  isFilesystemRoot,
} from "../../path-validation.js"
import { PathTraversalError } from "../../errors/index.js"
import type {
  ManifestEntry,
  TemplateManifest,
  ManifestDiffResult,
} from "../../types.js"

/**
 * Bounded concurrency for batched FS operations on the render hot path.
 * 16 is well under macOS's default 256 open-FD ulimit while saturating
 * the small-file SSD workload templates produce.
 */
const BATCH_IO_CONCURRENCY = 16

// ---------------------------------------------------------------------------
// Hashing
// ---------------------------------------------------------------------------

/** Compute a SHA-256 hex digest of file content. */
export function hashFileContent(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex")
}

// ---------------------------------------------------------------------------
// FileManifestStore — in-memory store mapping templateId -> TemplateManifest
// ---------------------------------------------------------------------------

export class FileManifestStore {
  private manifests = new Map<string, TemplateManifest>()

  /** Retrieve the manifest for a template ID, or undefined if absent. */
  get(templateId: string): TemplateManifest | undefined {
    return this.manifests.get(templateId)
  }

  /** Store a manifest for a template ID. */
  set(templateId: string, manifest: TemplateManifest): void {
    this.manifests.set(templateId, manifest)
  }

  /** Remove a manifest for a template ID. */
  delete(templateId: string): void {
    this.manifests.delete(templateId)
  }

  /** Remove all manifests (useful for testing). */
  clear(): void {
    this.manifests.clear()
  }
}

// ---------------------------------------------------------------------------
// Global singleton
// ---------------------------------------------------------------------------

const globalManifestStore = new FileManifestStore()

/** Return the global manifest store instance. */
export function getManifestStore(): FileManifestStore {
  return globalManifestStore
}

// ---------------------------------------------------------------------------
// Build manifest from directory
// ---------------------------------------------------------------------------

/**
 * A manifest entry plus the file content used to compute its hash. Returned
 * by {@link buildManifestFromDirectoryWithContent} so the cold-render path
 * can populate its in-memory content map without re-reading the same files.
 */
export interface ManifestEntryWithContent extends ManifestEntry {
  readonly content: string
}

/**
 * Scan a directory recursively and build a manifest of all files with their
 * SHA-256 content hashes and content. Reads run in parallel at
 * {@link BATCH_IO_CONCURRENCY}.
 */
export function buildManifestFromDirectoryWithContent(rootDir: string) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem

    const walkEntries = yield* fs.walk(rootDir).pipe(
      Stream.filter((e) => e.isFile),
      Stream.runCollect,
    )
    const files = Chunk.toReadonlyArray(walkEntries)

    const entries = yield* Effect.forEach(
      files,
      (entry) =>
        fs.readFile(entry.path).pipe(
          Effect.map(
            (content) =>
              ({
                path: entry.relativePath,
                contentHash: hashFileContent(content),
                content,
              }) satisfies ManifestEntryWithContent,
          ),
        ),
      { concurrency: BATCH_IO_CONCURRENCY },
    )

    return entries
  })
}

/**
 * Scan a directory recursively and build a manifest of all files with their
 * SHA-256 content hashes. Thin wrapper around
 * {@link buildManifestFromDirectoryWithContent} that drops the content field.
 */
export function buildManifestFromDirectory(rootDir: string) {
  return buildManifestFromDirectoryWithContent(rootDir).pipe(
    Effect.map((entries) =>
      entries.map(
        ({ path, contentHash }) =>
          ({ path, contentHash }) satisfies ManifestEntry,
      ),
    ),
  )
}

// ---------------------------------------------------------------------------
// Diff computation
// ---------------------------------------------------------------------------

/**
 * Compare old and new manifest entries to determine what actions are needed.
 *
 * Returns which files are orphaned (in old but not new), created (in new but
 * not old), modified (in both but different hash), or unchanged.
 */
export function computeDiff(
  oldEntries: ManifestEntry[],
  newEntries: ManifestEntry[],
): ManifestDiffResult {
  const oldMap = new Map<string, string>()
  for (const e of oldEntries) {
    oldMap.set(e.path, e.contentHash)
  }

  const newMap = new Map<string, string>()
  for (const e of newEntries) {
    newMap.set(e.path, e.contentHash)
  }

  const orphaned: string[] = []
  const created: string[] = []
  const modified: string[] = []
  const unchanged: string[] = []

  // Files in old but not in new — orphaned
  for (const path of oldMap.keys()) {
    if (!newMap.has(path)) {
      orphaned.push(path)
    }
  }

  // Categorise new files
  for (const [path, newHash] of newMap) {
    const oldHash = oldMap.get(path)
    if (oldHash === undefined) {
      created.push(path)
    } else if (oldHash === newHash) {
      unchanged.push(path)
    } else {
      modified.push(path)
    }
  }

  return { orphaned, created, modified, unchanged }
}

// ---------------------------------------------------------------------------
// Diff-path safety
// ---------------------------------------------------------------------------

/**
 * Validate that every path in a diff is a "safe" relative path — no `..`
 * segments, no absolute paths. The diff drives `fs.rm` and `fs.writeFile`
 * against `outputDir`, so a malicious or buggy entry like `../etc/passwd`
 * would otherwise resolve outside the output dir.
 *
 * Caller-buggy input fails the whole apply with a PathTraversalError before
 * any filesystem operation runs.
 */
function assertSafeDiffPaths(diff: ManifestDiffResult) {
  return Effect.sync(() => undefined).pipe(
    Effect.flatMap(() => {
      const buckets: Array<readonly [string, readonly string[]]> = [
        ["created", diff.created],
        ["modified", diff.modified],
        ["orphaned", diff.orphaned],
        ["unchanged", diff.unchanged],
      ]
      for (const [bucket, paths] of buckets) {
        for (const p of paths) {
          if (!p) {
            return Effect.fail(
              new PathTraversalError({
                path: p,
                message: `manifest diff ${bucket} entry is empty`,
              }),
            )
          }
          if (isAbsolutePath(p)) {
            return Effect.fail(
              new PathTraversalError({
                path: p,
                message: `manifest diff ${bucket} contains absolute path`,
              }),
            )
          }
          if (containsPathTraversal(p)) {
            return Effect.fail(
              new PathTraversalError({
                path: p,
                message: `manifest diff ${bucket} contains '..' traversal`,
              }),
            )
          }
        }
      }
      return Effect.void
    }),
  )
}

// ---------------------------------------------------------------------------
// Apply diff — patch the real output directory from a rendered source tree
// ---------------------------------------------------------------------------

/**
 * Result of applying a diff.
 */
export interface ApplyDiffResult {
  readonly written: number
  readonly deleted: number
}

/**
 * Copy a single file from sourceDir to outputDir, preserving the relative path
 * and creating parent directories as needed.
 */
function copyFileForManifest(
  sourceDir: string,
  outputDir: string,
  relPath: string,
) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem
    const srcPath = path.join(sourceDir, relPath)
    const dstPath = path.join(outputDir, relPath)

    // Use buffer read/write so binary files round-trip intact.
    const content = yield* fs.readFileBuffer(srcPath)
    yield* fs.mkdir(path.dirname(dstPath), { recursive: true })
    yield* fs.writeFile(dstPath, content)
  })
}

/**
 * Walk up from `dir` removing empty directories, stopping at `stopAt`.
 * Never removes `stopAt` itself, anything outside `stopAt`, or a filesystem
 * root. Silently ignores removal failures (non-empty, permission, etc.).
 */
function cleanupEmptyParentDirs(dir: string, stopAt: string) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem
    let current = dir
    while (current !== stopAt && current !== "." && !isFilesystemRoot(current)) {
      if (!isContainedIn(current, stopAt)) return
      const entries = yield* fs.readdir(current).pipe(Effect.either)
      if (entries._tag === "Left" || entries.right.length > 0) return
      // `fs.rm` without `recursive: true` fails on directories. Since the
      // readdir check above confirmed `current` is empty, recursive is safe
      // — it just means "use the directory-aware path".
      const removed = yield* fs.rm(current, { recursive: true }).pipe(Effect.either)
      if (removed._tag === "Left") return
      current = path.dirname(current)
    }
  })
}

/**
 * Two siblings racing to remove the same parent is harmless:
 * cleanupEmptyParentDirs swallows the loser's "not empty" / "not found" rm.
 */
function deleteOrphans(orphaned: readonly string[], outputDir: string) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem
    const results = yield* Effect.forEach(
      orphaned,
      (relPath) =>
        Effect.gen(function* () {
          const fullPath = path.join(outputDir, relPath)
          const ok = yield* Effect.isSuccess(fs.rm(fullPath, { force: true }))
          yield* cleanupEmptyParentDirs(path.dirname(fullPath), outputDir)
          return ok
        }),
      { concurrency: BATCH_IO_CONCURRENCY },
    )
    return results.filter(Boolean).length
  })
}

function restoreMissingUnchanged<E, R>(
  unchanged: readonly string[],
  outputDir: string,
  restore: (relPath: string) => Effect.Effect<void, E, R>,
) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem
    const results = yield* Effect.forEach(
      unchanged,
      (relPath) =>
        Effect.gen(function* () {
          const fullPath = path.join(outputDir, relPath)
          const exists = yield* fs.exists(fullPath)
          if (exists) return false
          yield* restore(relPath)
          return true
        }),
      { concurrency: BATCH_IO_CONCURRENCY },
    )
    return results.filter(Boolean).length
  })
}

/**
 * Apply a manifest diff by patching `outputDir` to match `sourceDir`:
 *  - delete orphaned files (present in the prior manifest but not the new one)
 *  - copy created and modified files from `sourceDir` to `outputDir`
 *  - leave unchanged files alone, but recreate them if the user manually
 *    deleted them between renders
 *
 * Orphan scope is manifest-based, so files in `outputDir` that this template
 * never produced are never touched — safe to run against a shared worktree.
 */
export function applyDiff(
  diff: ManifestDiffResult,
  sourceDir: string,
  outputDir: string,
) {
  return Effect.gen(function* () {
    yield* assertSafeDiffPaths(diff)
    const deleted = yield* deleteOrphans(diff.orphaned, outputDir)

    // Write created + modified files in one parallel batch — they're
    // independent and skipping the barrier between them avoids latency
    // when one bucket is much smaller than the other.
    const writes = [...diff.created, ...diff.modified]
    yield* Effect.forEach(
      writes,
      (relPath) => copyFileForManifest(sourceDir, outputDir, relPath),
      { concurrency: BATCH_IO_CONCURRENCY },
    )

    const restored = yield* restoreMissingUnchanged(
      diff.unchanged,
      outputDir,
      (relPath) => copyFileForManifest(sourceDir, outputDir, relPath),
    )

    return { written: writes.length + restored, deleted } satisfies ApplyDiffResult
  })
}

/**
 * Like {@link applyDiff} but the source is an in-memory {path → content} map
 * rather than a directory on disk. Used by the warm-render path where the
 * boilerplate WASM bridge hands us file contents directly and there's no
 * tempdir to copy from.
 *
 * Behavior matches {@link applyDiff} for orphans / unchanged restoration —
 * only the "write a created/modified file" branch differs.
 */
export function applyDiffFromContent(
  diff: ManifestDiffResult,
  contents: ReadonlyMap<string, string>,
  outputDir: string,
) {
  return Effect.gen(function* () {
    yield* assertSafeDiffPaths(diff)
    const fs = yield* FileSystem

    const writeFromContent = (relPath: string) =>
      Effect.gen(function* () {
        const content = contents.get(relPath)
        // Missing-content for a path the diff said to write is a caller bug —
        // failing loudly here beats silently leaving the file stale.
        if (content === undefined) {
          return yield* Effect.fail(
            new Error(`applyDiffFromContent: no content for "${relPath}"`),
          )
        }
        const dstPath = path.join(outputDir, relPath)
        yield* fs.mkdir(path.dirname(dstPath), { recursive: true })
        yield* fs.writeFile(dstPath, content)
      })

    const deleted = yield* deleteOrphans(diff.orphaned, outputDir)

    const writes = [...diff.created, ...diff.modified]
    yield* Effect.forEach(writes, writeFromContent, {
      concurrency: BATCH_IO_CONCURRENCY,
    })

    // With dirty-set rendering we may not have content cached for every
    // unchanged path (only what was re-rendered this call). Restore from
    // contentMap if available; otherwise rely on a future render-all to
    // bring the file back.
    const restorable = diff.unchanged.filter((p) => contents.has(p))
    const restored = yield* restoreMissingUnchanged(
      restorable,
      outputDir,
      writeFromContent,
    )

    return { written: writes.length + restored, deleted } satisfies ApplyDiffResult
  })
}
