/**
 * File manifest tracking — TypeScript port of api/file_manifest.go.
 *
 * Tracks files generated by template blocks to enable smart cleanup. When a
 * template re-renders with different variables, the manifest detects which
 * files are orphaned and should be deleted automatically.
 *
 * Implements "block-scoped file manifests" where each Template component
 * (identified by its ID) owns a specific set of generated files. On re-render
 * only files that are no longer produced are deleted, and only changed files
 * are rewritten.
 */

import { Effect, Stream } from "effect"
import crypto from "node:crypto"

import { FileSystem } from "../../services/FileSystem.js"
import { FileReadError } from "../../errors/index.js"
import type {
  ManifestEntry,
  TemplateManifest,
  ManifestDiffResult,
} from "../../types.js"

// ---------------------------------------------------------------------------
// Hashing
// ---------------------------------------------------------------------------

/** Compute a SHA-256 hex digest of file content. */
export function hashFileContent(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex")
}

// ---------------------------------------------------------------------------
// FileManifestStore — in-memory store mapping templateId -> TemplateManifest
// ---------------------------------------------------------------------------

export class FileManifestStore {
  private manifests = new Map<string, TemplateManifest>()

  /** Retrieve the manifest for a template ID, or undefined if absent. */
  get(templateId: string): TemplateManifest | undefined {
    return this.manifests.get(templateId)
  }

  /** Store a manifest for a template ID. */
  set(templateId: string, manifest: TemplateManifest): void {
    this.manifests.set(templateId, manifest)
  }

  /** Remove a manifest for a template ID. */
  delete(templateId: string): void {
    this.manifests.delete(templateId)
  }

  /** Remove all manifests (useful for testing). */
  clear(): void {
    this.manifests.clear()
  }
}

// ---------------------------------------------------------------------------
// Global singleton
// ---------------------------------------------------------------------------

const globalManifestStore = new FileManifestStore()

/** Return the global manifest store instance. */
export function getManifestStore(): FileManifestStore {
  return globalManifestStore
}

// ---------------------------------------------------------------------------
// Build manifest from directory
// ---------------------------------------------------------------------------

/**
 * Scan a directory recursively and build a manifest of all files with their
 * SHA-256 content hashes.
 *
 * Returns an Effect that requires the FileSystem service.
 */
export function buildManifestFromDirectory(rootDir: string) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem

    const entries: ManifestEntry[] = []

    // Collect walk entries into an array
    const walkEntries = yield* Stream.runCollect(fs.walk(rootDir))

    for (const entry of walkEntries) {
      if (!entry.isFile) continue

      const content = yield* fs.readFile(entry.path)
      entries.push({
        path: entry.relativePath,
        contentHash: hashFileContent(content),
      })
    }

    return entries
  })
}

// ---------------------------------------------------------------------------
// Diff computation
// ---------------------------------------------------------------------------

/**
 * Compare old and new manifest entries to determine what actions are needed.
 *
 * Returns which files are orphaned (in old but not new), created (in new but
 * not old), modified (in both but different hash), or unchanged.
 */
export function computeDiff(
  oldEntries: ManifestEntry[],
  newEntries: ManifestEntry[],
): ManifestDiffResult {
  const oldMap = new Map<string, string>()
  for (const e of oldEntries) {
    oldMap.set(e.path, e.contentHash)
  }

  const newMap = new Map<string, string>()
  for (const e of newEntries) {
    newMap.set(e.path, e.contentHash)
  }

  const orphaned: string[] = []
  const created: string[] = []
  const modified: string[] = []
  const unchanged: string[] = []

  // Files in old but not in new — orphaned
  for (const path of oldMap.keys()) {
    if (!newMap.has(path)) {
      orphaned.push(path)
    }
  }

  // Categorise new files
  for (const [path, newHash] of newMap) {
    const oldHash = oldMap.get(path)
    if (oldHash === undefined) {
      created.push(path)
    } else if (oldHash === newHash) {
      unchanged.push(path)
    } else {
      modified.push(path)
    }
  }

  return { orphaned, created, modified, unchanged }
}
