/**
 * @fileoverview FilesWorkspace Component
 * 
 * Main container for the files workspace with dynamic tabs:
 * - "Generated" tab: shown when files are generated by Template/Command blocks
 * - "All files" tab: shown when a git worktree is registered (GitClone)
 * - "Changed" tab: shown when a git worktree is registered
 * 
 * When nothing is available, shows an empty state message.
 * When only one source exists (generated or worktree), the tab bar is simplified.
 */

import { useState, useMemo, useEffect, useRef } from 'react'
import { ChevronLeft, Folder, Copy, Check, FolderOpen } from 'lucide-react'
import { cn, copyTextToClipboard } from '@/lib/utils'
import { WorkspaceTabBar } from './WorkspaceTabBar'
import { WorkspaceMetadataBar } from './WorkspaceMetadataBar'
import { WorkspaceFileBrowser } from './WorkspaceFileBrowser'
import { ChangedFilesView } from './ChangedFilesView'
import { CodeFileCollection } from '../code/CodeFileCollection'
import { useGitWorkTree } from '@/contexts/GitWorkTreeContext'
import { useWorkspaceTree } from '@/hooks/useWorkspaceTree'
import { useWorkspaceChanges } from '@/hooks/useWorkspaceChanges'
import type { FileTreeNode } from '../code/FileTree'
import type { WorkspaceTab } from '@/types/workspace'

interface FilesWorkspaceProps {
  /** Generated files tree (from GeneratedFilesContext) */
  generatedFiles: FileTreeNode[];
  /** Additional CSS classes */
  className?: string;
  /** Callback to hide the workspace */
  onHide?: () => void;
  /** Whether to hide content (for animations) */
  hideContent?: boolean;
  /** Absolute path to generated files output */
  absoluteOutputPath?: string;
  /** Relative path to generated files output */
  relativeOutputPath?: string;
}

export const FilesWorkspace = ({
  generatedFiles,
  className = "",
  onHide,
  hideContent = false,
  absoluteOutputPath,
  relativeOutputPath,
}: FilesWorkspaceProps) => {
  const [activeTab, setActiveTab] = useState<WorkspaceTab>('generated')
  const hasAutoSwitched = useRef(false)
  
  // Git worktree data
  const { workTrees, activeWorkTree, activeWorkTreeId, setActiveWorkTree } = useGitWorkTree()
  const { tree: workspaceTree, isLoading: treeLoading, error: treeError, totalFiles, refetch: refetchTree } = useWorkspaceTree()
  const { changes, totalChanges, tooManyChanges, isLoading: changesLoading, fetchFileDiff } = useWorkspaceChanges()
  
  // Determine what's available
  const hasGeneratedFiles = generatedFiles.length > 0
  const hasWorkTree = workTrees.length > 0
  const hasNothing = !hasGeneratedFiles && !hasWorkTree
  
  // Calculate generated file count
  const generatedFileCount = useMemo(() => countFiles(generatedFiles), [generatedFiles])
  
  // Auto-switch to "All files" tab when first worktree is registered
  useEffect(() => {
    if (hasWorkTree && !hasAutoSwitched.current) {
      hasAutoSwitched.current = true
      setActiveTab('all')
    }
  }, [hasWorkTree])
  
  // Determine available tabs
  const availableTabs = useMemo(() => {
    const tabs: WorkspaceTab[] = []
    if (hasGeneratedFiles) tabs.push('generated')
    if (hasWorkTree) tabs.push('all', 'changed')
    return tabs
  }, [hasGeneratedFiles, hasWorkTree])
  
  // Ensure active tab is valid
  useEffect(() => {
    if (availableTabs.length > 0 && !availableTabs.includes(activeTab)) {
      setActiveTab(availableTabs[0])
    }
  }, [availableTabs, activeTab])
  
  // Tab counts for badges
  const tabCounts = useMemo(() => ({
    generated: generatedFileCount,
    changed: totalChanges,
  }), [generatedFileCount, totalChanges])
  
  // Change stats for the metadata bar
  const changeStats = useMemo(() => {
    const added = changes.filter(c => c.changeType === 'added').length
    const modified = changes.filter(c => c.changeType === 'modified').length
    const deleted = changes.filter(c => c.changeType === 'deleted').length
    const totalAdditions = changes.reduce((sum, c) => sum + c.additions, 0)
    const totalDeletions = changes.reduce((sum, c) => sum + c.deletions, 0)
    return { added, modified, deleted, totalAdditions, totalDeletions, total: changes.length }
  }, [changes])
  
  // Git info for metadata bar
  const gitInfo = useMemo(() => {
    if (!activeWorkTree) return null
    return activeWorkTree.gitInfo
  }, [activeWorkTree])

  // Empty state: nothing to show
  if (hasNothing) {
    return (
      <div className={cn("w-full h-full flex flex-col", className)}>
        <div className="flex items-center justify-between py-2 px-4 lg:px-2">
          <h2 className="text-lg font-semibold text-gray-700">Files</h2>
          {onHide && (
            <button
              onClick={onHide}
              className="hidden lg:block p-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-all duration-200 cursor-pointer"
              title="Hide files workspace"
            >
              <ChevronLeft className="w-4 h-4 text-gray-600" />
            </button>
          )}
        </div>
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center px-8">
            <FolderOpen className="w-16 h-16 mx-auto mb-3 text-gray-300" />
            <p className="text-sm text-gray-500">
              Files generated by blocks and cloned repositories will appear here.
            </p>
          </div>
        </div>
      </div>
    )
  }

  // Only generated files: show content directly without tab bar
  const showTabBar = hasGeneratedFiles && hasWorkTree || (hasWorkTree && availableTabs.length > 1)

  return (
    <div className={cn("w-full h-full flex flex-col", className)}>
      {/* Header with title, worktree switcher, and hide button */}
      <div className="flex items-center justify-between py-2 px-4 lg:px-2">
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-semibold text-gray-700">Files</h2>
          
          {/* Worktree switcher (when 2+ worktrees) */}
          {workTrees.length >= 2 && (
            <select
              value={activeWorkTreeId ?? ''}
              onChange={(e) => setActiveWorkTree(e.target.value)}
              className="text-sm border border-gray-300 rounded-md px-2 py-1 bg-white text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              {workTrees.map(wt => (
                <option key={wt.id} value={wt.id}>
                  {wt.gitInfo.repoName || wt.id}
                </option>
              ))}
            </select>
          )}
        </div>
        
        {onHide && (
          <button
            onClick={onHide}
            className="hidden lg:block p-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-all duration-200 cursor-pointer"
            title="Hide files workspace"
          >
            <ChevronLeft className="w-4 h-4 text-gray-600" />
          </button>
        )}
      </div>
      
      {/* Tab Bar - only when multiple tab groups exist */}
      {showTabBar && (
        <WorkspaceTabBar
          activeTab={activeTab}
          onTabChange={setActiveTab}
          tabCounts={tabCounts}
          className="px-2"
          availableTabs={availableTabs}
        />
      )}
      
      {/* Metadata Bar */}
      {activeTab === 'changed' ? (
        <div className="flex items-center gap-3 px-4 py-2 bg-gray-50 text-sm">
          <span className="text-gray-600">
            <span className="font-medium">{changeStats.total}</span> changed {changeStats.total === 1 ? 'file' : 'files'}
          </span>
          <span className="text-gray-300">|</span>
          <span className="text-green-600 font-medium">+{changeStats.totalAdditions}</span>
          <span className="text-red-600 font-medium">-{changeStats.totalDeletions}</span>
          <ChangeProportionBar additions={changeStats.totalAdditions} deletions={changeStats.totalDeletions} />
        </div>
      ) : activeTab === 'generated' ? (
        <GeneratedFilesInfoBar 
          outputPath={absoluteOutputPath} 
          fileCount={generatedFileCount} 
        />
      ) : activeTab === 'all' ? (
        <WorkspaceMetadataBar
          gitInfo={gitInfo}
          localPath={activeWorkTree?.localPath}
          className="px-2"
        />
      ) : null}
      
      {/* Bordered content area */}
      <div className="flex-1 flex flex-col border-y border-gray-400 overflow-hidden">
        {activeTab === 'generated' && (
          <CodeFileCollection
            data={generatedFiles}
            className="h-full"
            hideContent={hideContent}
            absoluteOutputPath={absoluteOutputPath}
            relativeOutputPath={relativeOutputPath}
            hideHeader={true}
          />
        )}
        
        {activeTab === 'all' && (
          <WorkspaceFileBrowser
            tree={workspaceTree}
            isLoading={treeLoading}
            error={treeError}
            totalFiles={totalFiles}
            onRetry={refetchTree}
            className="h-full"
          />
        )}
        
        {activeTab === 'changed' && (
          <ChangedFilesView
            changes={changes}
            tooManyChanges={tooManyChanges}
            totalChanges={totalChanges}
            isLoading={changesLoading}
            onLoadDiff={fetchFileDiff}
            className="h-full"
          />
        )}
      </div>
    </div>
  )
}

/**
 * Info bar for Generated files tab showing local folder path and file count
 */
function GeneratedFilesInfoBar({ outputPath, fileCount }: { outputPath?: string; fileCount: number }) {
  const [didCopy, setDidCopy] = useState(false)
  
  const handleCopyPath = () => {
    if (outputPath) {
      setDidCopy(true)
      copyTextToClipboard(outputPath)
      setTimeout(() => setDidCopy(false), 1500)
    }
  }
  
  return (
    <div className="flex items-center justify-between px-4 py-2 bg-gray-50 text-sm">
      {outputPath ? (
        <div className="flex items-center gap-1.5 text-gray-700">
          <Folder className="w-4 h-4 text-gray-500" />
          <code className="font-mono text-xs text-gray-600">
            {outputPath}
          </code>
          <button
            onClick={handleCopyPath}
            className="p-0.5 text-gray-400 hover:text-gray-600 rounded cursor-pointer"
            title="Copy path"
          >
            {didCopy ? (
              <Check className="w-3.5 h-3.5 text-green-600" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
          </button>
        </div>
      ) : (
        <div className="flex items-center gap-1.5 text-gray-500">
          <Folder className="w-4 h-4" />
          <span className="italic text-xs">No output path specified</span>
        </div>
      )}
      
      <span className="text-gray-500 text-xs">
        <span className="font-medium text-gray-700">{fileCount}</span> {fileCount === 1 ? 'file' : 'files'} generated
      </span>
    </div>
  )
}

/**
 * Count total files in a file tree
 */
function countFiles(nodes: FileTreeNode[]): number {
  let count = 0
  for (const node of nodes) {
    if (node.type === 'file') {
      count++
    }
    if (node.children) {
      count += countFiles(node.children)
    }
  }
  return count
}

/**
 * GitHub-style proportion bar showing additions vs deletions
 */
function ChangeProportionBar({ additions, deletions }: { additions: number; deletions: number }) {
  const total = additions + deletions
  const BOXES = 5
  
  let greenBoxes = 0
  if (total > 0) {
    greenBoxes = Math.round((additions / total) * BOXES)
    if (additions > 0 && greenBoxes === 0) greenBoxes = 1
    if (deletions > 0 && greenBoxes === BOXES) greenBoxes = BOXES - 1
  }
  
  const redBoxes = BOXES - greenBoxes
  
  return (
    <div className="flex items-center gap-0.5">
      {Array.from({ length: greenBoxes }).map((_, i) => (
        <div key={`g-${i}`} className="w-2 h-2 rounded-sm bg-green-500" />
      ))}
      {Array.from({ length: redBoxes }).map((_, i) => (
        <div key={`r-${i}`} className="w-2 h-2 rounded-sm bg-red-500" />
      ))}
    </div>
  )
}
