/**
 * @fileoverview ProvenanceBadge Component
 * 
 * Small badge showing which block last generated or modified a file.
 * Clickable to scroll to the referenced block in the runbook.
 */

import { Terminal, FileCode, CheckCircle } from 'lucide-react'
import { cn } from '@/lib/utils'

interface ProvenanceBadgeProps {
  /** The block ID that last touched this file */
  sourceBlockId: string
  /** The block type (command, check, template) */
  sourceBlockType: string
  /** Whether this is in the "Generated" or "Changed" context */
  variant?: 'generated' | 'changed'
  /** Additional CSS classes */
  className?: string
}

const blockTypeIcons: Record<string, typeof Terminal> = {
  command: Terminal,
  check: CheckCircle,
  template: FileCode,
}

const blockTypeLabels: Record<string, string> = {
  command: 'Command',
  check: 'Check',
  template: 'Template',
}

export function ProvenanceBadge({
  sourceBlockId,
  sourceBlockType,
  variant = 'changed',
  className,
}: ProvenanceBadgeProps) {
  const Icon = blockTypeIcons[sourceBlockType] || Terminal
  const label = blockTypeLabels[sourceBlockType] || sourceBlockType
  const prefix = variant === 'generated' ? 'Last generated by' : 'Last modified by'

  const handleClick = () => {
    // Scroll to the block in the runbook using the block's ID anchor
    const blockElement = document.getElementById(sourceBlockId)
    if (blockElement) {
      blockElement.scrollIntoView({ behavior: 'smooth', block: 'center' })
    }
  }

  return (
    <button
      onClick={handleClick}
      className={cn(
        "inline-flex items-center gap-1 px-1.5 py-0.5 text-[10px] rounded-full",
        "bg-gray-100 text-gray-500 hover:bg-gray-200 hover:text-gray-700",
        "transition-colors cursor-pointer",
        className
      )}
      title={`${prefix} ${sourceBlockId} (${label})`}
    >
      <Icon className="w-2.5 h-2.5" />
      <span className="truncate max-w-[120px]">{sourceBlockId}</span>
    </button>
  )
}
