#!/bin/bash
# Generate configuration files using project variables
# Files are written to $RUNBOOKS_OUTPUT and captured to /generated

set -euo pipefail

echo "Generating configuration files..."
echo ""

# Verify RUNBOOKS_OUTPUT is available
if [ -z "${RUNBOOKS_OUTPUT:-}" ]; then
    echo "❌ Error: RUNBOOKS_OUTPUT is not set"
    echo "This variable is automatically provided by the Runbooks server."
    exit 1
fi

# Verify project variables are set
if [ -z "${PROJECT_NAME:-}" ]; then
    echo "❌ Error: PROJECT_NAME is not set"
    echo "Please run 'Set project variables' first."
    exit 1
fi

echo "📁 Output directory: $RUNBOOKS_OUTPUT"
echo "📦 Project: $PROJECT_NAME ($ENVIRONMENT)"
echo ""

# Create directories
mkdir -p "$RUNBOOKS_OUTPUT/tofu"
mkdir -p "$RUNBOOKS_OUTPUT/scripts"

# -----------------------------------------------------------------------------
# Generate config.json
# -----------------------------------------------------------------------------
echo "Creating config.json..."
cat > "$RUNBOOKS_OUTPUT/config.json" << EOF
{
  "project": {
    "name": "${PROJECT_NAME}",
    "environment": "${ENVIRONMENT}",
    "team_email": "${TEAM_EMAIL}",
    "cost_center": "${COST_CENTER}"
  },
  "infrastructure": {
    "aws_region": "${AWS_REGION}",
    "aws_account_id": "${AWS_ACCOUNT_ID}"
  },
  "application": {
    "port": ${APP_PORT},
    "replicas": ${REPLICA_COUNT}
  },
  "generated": {
    "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
    "generator": "runbooks"
  }
}
EOF

# -----------------------------------------------------------------------------
# Generate OpenTofu variables.tf
# -----------------------------------------------------------------------------
echo "Creating tofu/variables.tf..."
cat > "$RUNBOOKS_OUTPUT/tofu/variables.tf" << 'EOF'
# =============================================================================
# Variables for the infrastructure
# Generated by Runbooks
# =============================================================================

variable "project_name" {
  description = "Name of the project"
  type        = string
EOF
echo "  default     = \"${PROJECT_NAME}\"" >> "$RUNBOOKS_OUTPUT/tofu/variables.tf"
cat >> "$RUNBOOKS_OUTPUT/tofu/variables.tf" << 'EOF'
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)"
  type        = string
EOF
echo "  default     = \"${ENVIRONMENT}\"" >> "$RUNBOOKS_OUTPUT/tofu/variables.tf"
cat >> "$RUNBOOKS_OUTPUT/tofu/variables.tf" << 'EOF'
}

variable "aws_region" {
  description = "AWS region for deployment"
  type        = string
EOF
echo "  default     = \"${AWS_REGION}\"" >> "$RUNBOOKS_OUTPUT/tofu/variables.tf"
cat >> "$RUNBOOKS_OUTPUT/tofu/variables.tf" << 'EOF'
}

variable "team_email" {
  description = "Team contact email for notifications"
  type        = string
EOF
echo "  default     = \"${TEAM_EMAIL}\"" >> "$RUNBOOKS_OUTPUT/tofu/variables.tf"
cat >> "$RUNBOOKS_OUTPUT/tofu/variables.tf" << 'EOF'
}

variable "app_port" {
  description = "Port the application listens on"
  type        = number
EOF
echo "  default     = ${APP_PORT}" >> "$RUNBOOKS_OUTPUT/tofu/variables.tf"
cat >> "$RUNBOOKS_OUTPUT/tofu/variables.tf" << 'EOF'
}

variable "replica_count" {
  description = "Number of application replicas"
  type        = number
EOF
echo "  default     = ${REPLICA_COUNT}" >> "$RUNBOOKS_OUTPUT/tofu/variables.tf"
cat >> "$RUNBOOKS_OUTPUT/tofu/variables.tf" << 'EOF'
}
EOF

# -----------------------------------------------------------------------------
# Generate OpenTofu main.tf
# -----------------------------------------------------------------------------
echo "Creating tofu/main.tf..."
cat > "$RUNBOOKS_OUTPUT/tofu/main.tf" << 'EOF'
# =============================================================================
# Main OpenTofu Configuration
# Generated by Runbooks
# =============================================================================

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    # Configure your backend here
    # bucket = "your-terraform-state-bucket"
    # key    = "state/${var.project_name}/${var.environment}/terraform.tfstate"
    # region = var.aws_region
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "OpenTofu"
      GeneratedBy = "Runbooks"
      TeamEmail   = var.team_email
    }
  }
}

# -----------------------------------------------------------------------------
# Example Resources
# -----------------------------------------------------------------------------

resource "aws_s3_bucket" "app_data" {
  bucket = "${var.project_name}-${var.environment}-data"
}

resource "aws_s3_bucket_versioning" "app_data" {
  bucket = aws_s3_bucket.app_data.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_security_group" "app" {
  name        = "${var.project_name}-${var.environment}-app-sg"
  description = "Security group for ${var.project_name} application"

  ingress {
    from_port   = var.app_port
    to_port     = var.app_port
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
    description = "Allow internal traffic to app port"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound traffic"
  }

  tags = {
    Name = "${var.project_name}-${var.environment}-app-sg"
  }
}
EOF

# -----------------------------------------------------------------------------
# Generate OpenTofu outputs.tf
# -----------------------------------------------------------------------------
echo "Creating tofu/outputs.tf..."
cat > "$RUNBOOKS_OUTPUT/tofu/outputs.tf" << 'EOF'
# =============================================================================
# Outputs
# Generated by Runbooks
# =============================================================================

output "s3_bucket_name" {
  description = "Name of the S3 bucket for application data"
  value       = aws_s3_bucket.app_data.id
}

output "s3_bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = aws_s3_bucket.app_data.arn
}

output "security_group_id" {
  description = "ID of the application security group"
  value       = aws_security_group.app.id
}

output "project_info" {
  description = "Project configuration summary"
  value = {
    name        = var.project_name
    environment = var.environment
    region      = var.aws_region
    team        = var.team_email
  }
}
EOF

# -----------------------------------------------------------------------------
# Generate deployment script
# -----------------------------------------------------------------------------
echo "Creating scripts/deploy.sh..."
cat > "$RUNBOOKS_OUTPUT/scripts/deploy.sh" << EOF
#!/bin/bash
# =============================================================================
# Deployment Script for ${PROJECT_NAME}
# Generated by Runbooks
# =============================================================================

set -euo pipefail

PROJECT="${PROJECT_NAME}"
ENV="${ENVIRONMENT}"
REGION="${AWS_REGION}"

echo "🚀 Deploying \$PROJECT to \$ENV in \$REGION"
echo ""

# Navigate to OpenTofu directory
cd "\$(dirname "\$0")/../tofu"

# Initialize OpenTofu
echo "📦 Initializing OpenTofu..."
tofu init

# Plan changes
echo ""
echo "📋 Planning changes..."
tofu plan -out=tfplan

# Prompt for confirmation
echo ""
read -p "Apply changes? (y/N) " -n 1 -r
echo
if [[ \$REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "⚡ Applying changes..."
    tofu apply tfplan
    echo ""
    echo "✅ Deployment complete!"
else
    echo "Deployment cancelled."
fi
EOF
chmod +x "$RUNBOOKS_OUTPUT/scripts/deploy.sh"

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo ""
echo "✅ Generated files:"
find "$RUNBOOKS_OUTPUT" -type f | sort | while read file; do
    relpath="${file#$RUNBOOKS_OUTPUT/}"
    size=$(wc -c < "$file" | tr -d ' ')
    echo "   📄 $relpath ($size bytes)"
done

echo ""
echo "These files will appear in the Generated Files panel"
echo "and are saved to your project's /generated folder."
