// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AwsService is the Wails IPC wrapper around the AWS handlers in
 * the legacy Gin server. Every method corresponds 1:1 to a
 * /api/aws/* endpoint so migrating the frontend hook
 * (web/src/components/mdx/AwsAuth/hooks/useAwsAuth.ts) is a
 * per-method drop-in replacement.
 * 
 * Validate uses the AwsClient port so it stays testable with a fake
 * adapter. The SSO + profile methods still reach the SDK directly via
 * shared helpers in api/aws_auth_ops.go — the v1 desktop adapter
 * already does that work in-process, and a future hosted adapter can
 * replace the whole surface by swapping this service for one that
 * talks to a tenant-scoped AWS port.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckRegion asks the Account API whether a region is enabled for
 * the caller's account.
 */
export function CheckRegion(req: api$0.CheckRegionRequest): $CancellablePromise<api$0.CheckRegionResponse | null> {
    return $Call.ByID(2792525075, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ConfirmEnvCredentials reads (prefixed) AWS credentials from the
 * process environment, validates them, and writes them to the open
 * gruntbook's session environment so exec inherits them. Returns
 * the credentials back so the frontend can associate them with a
 * specific AwsAuth block (awsAuthId feature).
 */
export function ConfirmEnvCredentials(req: api$0.ConfirmEnvCredentialsRequest): $CancellablePromise<api$0.ConfirmEnvCredentialsResponse | null> {
    return $Call.ByID(600440488, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * EnvCredentials reads (prefixed) AWS credentials from the process
 * environment and validates them via STS. Returns only metadata —
 * raw credentials never leave the process on the detection path.
 * Call ConfirmEnvCredentials to actually register them to the
 * session.
 */
export function EnvCredentials(req: api$0.EnvCredentialsRequest): $CancellablePromise<api$0.EnvCredentialsResponse | null> {
    return $Call.ByID(2264980318, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ProfileAuth authenticates using a local AWS profile.
 */
export function ProfileAuth(req: api$0.ProfileAuthRequest): $CancellablePromise<api$0.ProfileAuthResponse | null> {
    return $Call.ByID(1510674448, req).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Profiles returns the AWS profiles discovered in ~/.aws/credentials
 * and ~/.aws/config on the local machine.
 */
export function Profiles(): $CancellablePromise<$models.ProfilesResponse | null> {
    return $Call.ByID(1390148075).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SsoComplete exchanges an access token + account + role for
 * short-lived role credentials, validating them via STS.
 */
export function SsoComplete(req: api$0.SSOCompleteRequest): $CancellablePromise<api$0.SSOCompleteResponse | null> {
    return $Call.ByID(4172498367, req).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SsoListRoles lists roles available for a given SSO account (used
 * during the account-picker step after SsoPoll returns
 * select_account).
 */
export function SsoListRoles(req: api$0.SSOListRolesRequest): $CancellablePromise<api$0.SSOListRolesResponse | null> {
    return $Call.ByID(901094937, req).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SsoPoll polls for SSO authentication completion. The response's
 * Status field drives the UI state machine (pending / failed /
 * success / select_account).
 */
export function SsoPoll(req: api$0.SSOPollRequest): $CancellablePromise<api$0.SSOPollResponse | null> {
    return $Call.ByID(2367579605, req).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SsoStart initiates AWS IAM Identity Center device authorization.
 * The UI takes the returned VerificationUri + UserCode, opens the
 * browser, and polls SsoPoll until the user completes the flow.
 */
export function SsoStart(req: api$0.SSOStartRequest): $CancellablePromise<api$0.SSOStartResponse | null> {
    return $Call.ByID(1909701220, req).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Validate validates manual AWS credentials (access key ID +
 * secret + optional session token + target region). Delegates to the
 * core/aws.Validate path via api.ValidateAwsCredentials.
 */
export function Validate(req: api$0.ValidateCredentialsRequest): $CancellablePromise<api$0.ValidateCredentialsResponse | null> {
    return $Call.ByID(2695635543, req).then(($result: any) => {
        return $$createType19($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.CheckRegionResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = api$0.ConfirmEnvCredentialsResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = api$0.EnvCredentialsResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = api$0.ProfileAuthResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.ProfilesResponse.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = api$0.SSOCompleteResponse.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = api$0.SSOListRolesResponse.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = api$0.SSOPollResponse.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = api$0.SSOStartResponse.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = api$0.ValidateCredentialsResponse.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
