// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoilerplateService exposes the boilerplate.yml parser used by the
 * <Inputs> and <Template> blocks. Today this is read-only: the frontend
 * asks for variables + output-dependency metadata and renders a form.
 * 
 * Semantics mirror the legacy `POST /api/boilerplate/variables` handler
 * (see api.HandleBoilerplateRequest) so the migrated frontend hook
 * doesn't observe a behavior change when the transport switches.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

/**
 * ParseVariables parses a boilerplate.yml — either one referenced by
 * templatePath (resolved relative to the open gruntbook) or inline
 * boilerplateContent — and returns the variable declarations.
 */
export function ParseVariables(req: api$0.BoilerplateRequest): $CancellablePromise<api$0.BoilerplateConfig | null> {
    return $Call.ByID(2677509515, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.BoilerplateConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
