// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecService is the Wails IPC wrapper around the api.RunExec* helpers.
 * 
 * Today's HTTP /api/exec endpoint streams output via Server-Sent Events
 * on the same connection. The IPC version inverts that: Run returns a
 * runID immediately and pushes events through the Wails emitter under
 * topic-scoped channels (`exec:<runID>:log`, `exec:<runID>:status`,
 * `exec:<runID>:outputs`, `exec:<runID>:files_captured`,
 * `exec:<runID>:error`, `exec:<runID>:done`). The frontend subscribes
 * with Events.On(topic, cb) keyed off the runID. This also makes
 * Cancel(runID) natural — something that was awkward over SSE.
 * 
 * Setup errors (invalid session, missing executable, template render
 * failure, temp-dir creation) surface synchronously as Run's error
 * return. Execution-time issues (non-zero exit, timeout) arrive
 * through the event channels, matching the legacy SSE shape.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops an in-flight run. No-op if the runID is unknown (the
 * run may have already finished). Cancellation propagates via the
 * context that RunExecStream is executing under, so the running
 * process receives SIGKILL from the stdlib's exec.CommandContext.
 */
export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3121775461, runID);
}

/**
 * Run starts an exec run asynchronously. Validates the session and
 * prepares all temp resources synchronously (so authoring/setup errors
 * are returned as errors, not event-stream errors), then launches a
 * goroutine that streams output under `exec:<runID>:*` topics.
 * 
 * SessionID is the same Bearer token the HTTP client uses — M4 reuses
 * the SessionManager from the embedded Gin server so the two
 * transports see the same session state (env vars, worktree, exec
 * count). Leave it empty during bootstrapping (before a session
 * exists); Run will reject with a clear error.
 */
export function Run(sessionID: string, req: api$0.ExecRequest): $CancellablePromise<$models.ExecRunResult | null> {
    return $Call.ByID(3286206660, sessionID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExecRunResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
