// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes reads of the currently-open gruntbook and files
 * under its directory to the frontend over IPC.
 * 
 * Semantics mirror the `POST /api/file` HTTP handler: an empty
 * RelativePath returns the gruntbook.mdx itself; a relative path is
 * resolved against filepath.Dir(gruntbookPath). Reads outside the
 * gruntbook directory are refused.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Read returns a file from the currently-open gruntbook's directory.
 * An empty relPath returns the gruntbook.mdx itself. relPath must stay
 * inside the gruntbook directory; ".." escapes are rejected.
 */
export function Read(relPath: string): $CancellablePromise<$models.FileResult | null> {
    return $Call.ByID(1007316572, relPath).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FileResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
