// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GeneratedFilesService exposes the output-directory inspection and
 * clear-all operations to the frontend over Wails IPC. It mirrors
 * GET /api/generated-files/check and DELETE /api/generated-files/delete.
 * 
 * Path resolution uses the currently-open gruntbook's WorkingDir +
 * OutputPath, so a call made while no gruntbook is open is a logic
 * error from the caller and fails fast.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

/**
 * Check returns info about the output directory: whether it exists,
 * how many files it contains, and the absolute path it resolved to.
 */
export function Check(): $CancellablePromise<api$0.GeneratedFilesCheckResponse | null> {
    return $Call.ByID(2524653870).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete removes every file and subdirectory inside the output
 * directory, but preserves the directory itself (for downstream
 * watchers/IDE trees). A non-existent directory is treated as a
 * successful no-op.
 */
export function Delete(): $CancellablePromise<api$0.GeneratedFilesDeleteResponse | null> {
    return $Call.ByID(3397723081).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.GeneratedFilesCheckResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = api$0.GeneratedFilesDeleteResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
