// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitHubService is the Wails IPC wrapper around the GitHub handlers in
 * the legacy Gin server. Every method corresponds 1:1 to a
 * /api/github/* endpoint so migrating the frontend hooks is a
 * per-method drop-in replacement.
 * 
 * Validate uses the GitHubClient port so it stays testable with a fake
 * adapter. The OAuth / list / credential-detection helpers still reach
 * the GitHub REST API directly via api.doGitHubAPIGet / doGitHubAPIPost
 * — the v1 desktop adapter already does that work in-process, and a
 * future hosted adapter can replace the whole surface by swapping this
 * service for one that talks to a tenant-scoped GitHub port.
 * 
 * Git-filesystem operations (clone, push, delete-branch) and the
 * streaming PR-creation flow are not exposed here; they belong to
 * GitService (task #43) because they orchestrate the `git` binary
 * rather than the GitHub REST API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

/**
 * CliCredentials detects GitHub credentials from the `gh` CLI, validates
 * them, and registers them to the open gruntbook's session. Returns only
 * user metadata + scopes. Matches the legacy /api/github/cli-credentials
 * endpoint.
 */
export function CliCredentials(): $CancellablePromise<api$0.GitHubCliCredentialsResponse | null> {
    return $Call.ByID(2188777741).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * EnvCredentials reads (prefixed) GitHub credentials from the process
 * environment, validates them, and registers them to the open
 * gruntbook's session. Returns only user metadata + scopes — the raw
 * token never leaves the process. Matches the legacy
 * /api/github/env-credentials endpoint.
 */
export function EnvCredentials(req: api$0.GitHubEnvCredentialsRequest): $CancellablePromise<api$0.GitHubEnvCredentialsResponse | null> {
    return $Call.ByID(1507347362, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListLabels returns labels for a given owner/repo. Matches
 * /api/github/labels.
 */
export function ListLabels(req: api$0.GitHubListLabelsRequest): $CancellablePromise<api$0.GitHubListLabelsResponse | null> {
    return $Call.ByID(3076093870, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListOrgs returns the authenticated user's organizations plus their
 * personal account. Requires an open gruntbook so the session token is
 * available. Matches /api/github/orgs.
 */
export function ListOrgs(): $CancellablePromise<api$0.GitHubListOrgsResponse | null> {
    return $Call.ByID(627593898).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListRefs returns branches and tags for a given owner/repo, optionally
 * filtered by query. Branches are sorted default-first. Matches
 * /api/github/refs.
 */
export function ListRefs(req: api$0.GitHubListRefsRequest): $CancellablePromise<api$0.GitHubListRefsResponse | null> {
    return $Call.ByID(1564401231, req).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListRepos returns repositories for the given owner, optionally
 * filtered by query. Matches /api/github/repos.
 */
export function ListRepos(req: api$0.GitHubListReposRequest): $CancellablePromise<api$0.GitHubListReposResponse | null> {
    return $Call.ByID(2763482862, req).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * OAuthPoll polls for OAuth completion. Status drives the UI state
 * machine (pending / complete / expired / error).
 */
export function OAuthPoll(req: api$0.GitHubOAuthPollRequest): $CancellablePromise<api$0.GitHubOAuthPollResponse | null> {
    return $Call.ByID(2060234713, req).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * OAuthStart initiates the GitHub OAuth device-authorization flow. The
 * UI uses the returned VerificationURI + UserCode to launch the browser
 * and then polls OAuthPoll until the user completes the flow.
 */
export function OAuthStart(req: api$0.GitHubOAuthStartRequest): $CancellablePromise<api$0.GitHubOAuthStartResponse | null> {
    return $Call.ByID(424812728, req).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Validate validates a GitHub token via the GitHubClient port. Matches
 * the legacy /api/github/validate HTTP handler.
 */
export function Validate(req: api$0.GitHubValidateRequest): $CancellablePromise<api$0.GitHubValidateResponse | null> {
    return $Call.ByID(2373732235, req).then(($result: any) => {
        return $$createType17($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.GitHubCliCredentialsResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = api$0.GitHubEnvCredentialsResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = api$0.GitHubListLabelsResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = api$0.GitHubListOrgsResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = api$0.GitHubListRefsResponse.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = api$0.GitHubListReposResponse.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = api$0.GitHubOAuthPollResponse.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = api$0.GitHubOAuthStartResponse.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = api$0.GitHubValidateResponse.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
