// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService is the Wails IPC wrapper around the filesystem git
 * operations that today's /api/git/* HTTP endpoints drive: clone, push,
 * open-pull-request, and delete-branch. The three streaming operations
 * return a runID immediately and push progress through the emitter
 * under `git:<runID>:<event>` topics, mirroring ExecService's pattern
 * (see ExecService Run → `exec:<runID>:*`). DeleteBranch is a plain
 * request/response since there's nothing to stream.
 * 
 * Event shapes on emitted topics match the legacy SSE events exactly
 * (ExecLogEvent / ExecStatusEvent / BlockOutputsEvent + named structs
 * for clone_result / pr_result / error), so the frontend's Zod schemas
 * work for both transports.
 * 
 * GitHub REST API calls live in GitHubService; this service handles the
 * `git` binary and repo filesystem state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops an in-flight run (clone, push, or pull-request). Idempotent
 * no-op when the runID is unknown — the run may have already finished,
 * or the frontend is calling Cancel on unmount without distinguishing.
 */
export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3269617002, runID);
}

/**
 * Clone starts a git clone asynchronously. Pre-flight validation runs
 * synchronously (URL shape, path-in-workdir, destination existence
 * with Force handling, token injection) and surfaces as
 * GitRunResult.CloneError when it fails. On success, RunID is returned
 * and the frontend subscribes to `git:<runID>:*` for streaming output.
 * 
 * Cancellation is via Cancel(runID). The 5-minute timeout matches the
 * legacy SSE handler so long-running clones surface a clear failure
 * rather than hanging indefinitely.
 */
export function Clone(req: api$0.GitCloneRequest): $CancellablePromise<$models.GitRunResult | null> {
    return $Call.ByID(3362211661, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteBranch deletes a local branch. Non-streaming: validation runs
 * synchronously (protected-branch list, currently-checked-out guard,
 * branch-name sanitization) and the git invocation is a quick
 * `git branch -D`. Matches the legacy DELETE /api/git/branch endpoint.
 */
export function DeleteBranch(req: api$0.GitDeleteBranchRequest): $CancellablePromise<api$0.GitDeleteBranchResponse | null> {
    return $Call.ByID(3240833923, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PullRequest creates a branch + commit + push + GitHub PR in one
 * flow. Emits step-by-step logs plus a `pr_result` event carrying the
 * PR URL/number. If the target branch already exists, emits an
 * `error` event with Code=branch_exists so the frontend can offer a
 * "use a different branch name" prompt (same shape as the legacy SSE
 * error event).
 */
export function PullRequest(req: api$0.CreatePullRequestRequest): $CancellablePromise<$models.GitRunResult | null> {
    return $Call.ByID(2493853968, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Push stages + commits + pushes the current branch to origin. Thin
 * wrapper over api.StreamGitPush with a runID + emitter sink.
 */
export function Push(req: api$0.GitPushRequest): $CancellablePromise<$models.GitRunResult | null> {
    return $Call.ByID(3285830676, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GitRunResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = api$0.GitDeleteBranchResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
