// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * DesktopStatus is the initial-state snapshot the Welcome page reads
 * on mount to decide whether to show itself or jump straight into the
 * runbook view.
 */
export class DesktopStatus {
    /**
     * InitialPath was provided via `gruntbooks desktop PATH` and is
     * empty when the user launched the app with no argument.
     */
    "initialPath": string;

    /**
     * GruntbookOpen is true once OpenLocal (or a pre-launch path) has
     * started the backend and a runbook is loaded.
     */
    "gruntbookOpen": boolean;

    /**
     * ServerPort is the bound Gin port (0 if not running).
     */
    "serverPort": number;

    /**
     * GruntbookPath mirrors OpenResult.GruntbookPath when a gruntbook
     * is open.
     */
    "gruntbookPath": string;

    /** Creates a new DesktopStatus instance. */
    constructor($$source: Partial<DesktopStatus> = {}) {
        if (!("initialPath" in $$source)) {
            this["initialPath"] = "";
        }
        if (!("gruntbookOpen" in $$source)) {
            this["gruntbookOpen"] = false;
        }
        if (!("serverPort" in $$source)) {
            this["serverPort"] = 0;
        }
        if (!("gruntbookPath" in $$source)) {
            this["gruntbookPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopStatus($$parsedSource as Partial<DesktopStatus>);
    }
}

/**
 * OpenResult is the return shape of OpenLocal (and, in later milestones,
 * OpenRemote). Carries everything the frontend needs to navigate from
 * the Welcome screen into the runbook view.
 */
export class OpenResult {
    /**
     * GruntbookPath is the resolved absolute path to gruntbook.mdx that
     * Gin is now serving.
     */
    "gruntbookPath": string;

    /**
     * DisplayPath is what the UI should show in the header. For local
     * opens it's the on-disk path; for remote opens (future) it's the
     * original URL.
     */
    "displayPath": string;

    /**
     * Port is the localhost port Gin bound to. The desktop asset
     * handler proxies /api/* to this port, so the frontend doesn't
     * hard-code it — this is surfaced for logging/debug only.
     */
    "port": number;

    /** Creates a new OpenResult instance. */
    constructor($$source: Partial<OpenResult> = {}) {
        if (!("gruntbookPath" in $$source)) {
            this["gruntbookPath"] = "";
        }
        if (!("displayPath" in $$source)) {
            this["displayPath"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenResult($$parsedSource as Partial<OpenResult>);
    }
}

/**
 * RecentEntry is one item in the recent-gruntbooks list. Exported for the
 * Wails bindings generator.
 */
export class RecentEntry {
    /**
     * Path is the absolute on-disk path (for local) or the original URL
     * (for remote) that the user opened. The frontend uses this as the
     * stable identifier; clicking a recent entry passes it straight to
     * OpenLocal or OpenRemote.
     */
    "path": string;

    /**
     * DisplayName is a short label. For local entries this is the
     * directory name; for remote entries it's the last non-empty URL
     * segment. Falls back to Path if nothing better can be derived.
     */
    "displayName": string;

    /**
     * IsRemote is true for git URLs, false for local paths. Lets the UI
     * show the right icon and dispatch to the right open action.
     */
    "isRemote": boolean;

    /**
     * LastOpened is when the entry was most recently opened.
     */
    "lastOpened": time$0.Time;

    /** Creates a new RecentEntry instance. */
    constructor($$source: Partial<RecentEntry> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("isRemote" in $$source)) {
            this["isRemote"] = false;
        }
        if (!("lastOpened" in $$source)) {
            this["lastOpened"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentEntry($$parsedSource as Partial<RecentEntry>);
    }
}
