// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RunbookService is the Wails IPC wrapper around the /api/gruntbook and
 * /api/gruntbook/executables HTTP endpoints. "Runbook" is the domain
 * noun for the open content; the new app is named Gruntbooks but the
 * runbook concept is unchanged, so the type keeps the noun.
 * 
 * Both methods are read-only snapshots of the currently-open gruntbook
 * sourced from serverManager.Config() / serverManager.Registry(). They
 * return typed shapes (not map[string]any) so the Wails TS codegen
 * renders concrete interfaces consumable by the existing frontend
 * hooks without runtime shape-checking.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Executables returns the executable registry for the currently-open
 * gruntbook. Live-reload mode (no registry) returns an empty map
 * matching the HTTP handler's behavior.
 */
export function Executables(): $CancellablePromise<$models.ExecutablesResult | null> {
    return $Call.ByID(1937210141).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Gruntbook returns the currently-open gruntbook's content and flags.
 * Errors when no gruntbook is open (user is still on Welcome) since
 * the frontend never asks for this before OpenLocal/OpenRemote returns.
 */
export function Gruntbook(): $CancellablePromise<$models.GruntbookResult | null> {
    return $Call.ByID(1845333803).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExecutablesResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GruntbookResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
