// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the Wails IPC wrapper around the /api/session/*
 * endpoints. Each method maps 1:1 to the legacy HTTP handler
 * (HandleCreateSession, HandleJoinSession, HandleGetSession,
 * HandleResetSession, HandleDeleteSession, HandleSetSessionEnv) and
 * returns the same JSON shape so the frontend's useSession context
 * works against both transports.
 * 
 * The session token concept is preserved end-to-end for M4 so Gin and
 * Wails share SessionManager state unchanged. M5 strips tokens when
 * the HTTP surface goes away — the IPC boundary itself is the trust
 * boundary.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create bootstraps a new session and returns its token. The working
 * directory is taken from the currently-open gruntbook's server
 * config, matching HandleCreateSession where the HTTP handler
 * captured it at bind time.
 */
export function Create(): $CancellablePromise<api$0.SessionTokenResponse | null> {
    return $Call.ByID(246186680).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete invalidates every token and drops session state. Currently
 * unused by the frontend but preserved for parity.
 */
export function Delete(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(843744615, sessionID);
}

/**
 * Get returns session metadata (workingDir, exec count, timestamps,
 * tab count). Requires a valid token — matches the HTTP path's
 * SessionAuthMiddleware guard.
 */
export function Get(sessionID: string): $CancellablePromise<api$0.SessionMetadata | null> {
    return $Call.ByID(886216152, sessionID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Join mints an additional token for an already-running session so a
 * second tab (or re-mount after StrictMode) can share env state with
 * the original. Returns nil when no session has been created yet,
 * mirroring the HTTP 401 from HandleJoinSession.
 */
export function Join(): $CancellablePromise<api$0.SessionTokenResponse | null> {
    return $Call.ByID(1225726860).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Reset restores the session's env to the snapshot captured at
 * creation time. Used by the "Reset session" UI control.
 */
export function Reset(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3114638075, sessionID);
}

/**
 * SetEnv appends env vars to the session. Used by AwsAuth and
 * GitHubAuth panels to inject credentials without running a script.
 */
export function SetEnv(sessionID: string, env: { [_ in string]?: string }): $CancellablePromise<$models.SessionSetEnvResult | null> {
    return $Call.ByID(3506234403, sessionID, env).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.SessionTokenResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = api$0.SessionMetadata.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.SessionSetEnvResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
