// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TelemetryService exposes the backend-computed telemetry configuration
 * (enabled flag, anonymous ID, build version) to the frontend over IPC.
 * 
 * The frontend uses this to decide whether to boot Mixpanel and which
 * anonymous identity to register with. In M3 this replaces the
 * GET /api/telemetry/config endpoint for desktop callers; browser mode
 * continues to hit the HTTP endpoint until M5 removes Gin.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as telemetry$0 from "../api/telemetry/models.js";

/**
 * Config returns the telemetry configuration snapshot. Safe to call
 * before the Mixpanel client is initialised; the snapshot reports
 * Enabled=false in that case.
 */
export function Config(): $CancellablePromise<telemetry$0.Config> {
    return $Call.ByID(3841031413).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = telemetry$0.Config.createFrom;
