// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TfService exposes OpenTofu/Terraform module parsing to the frontend
 * over Wails IPC. It mirrors the legacy `POST /api/tf/parse` handler.
 * 
 * A fresh TokenResolver is built per call so env/auth-helper changes
 * after the app launched (e.g. the user ran `gh auth login` in a new
 * terminal) are picked up immediately, matching the HTTP path.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

/**
 * Parse resolves a module source (local path relative to the open
 * gruntbook, or a remote git URL) and returns the boilerplate-shaped
 * variables plus module metadata.
 */
export function Parse(req: api$0.TfParseRequest): $CancellablePromise<api$0.TfParseResponse | null> {
    return $Call.ByID(4008472307, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.TfParseResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
