// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService polls the GitHub Releases API on startup and daily
 * thereafter to notify the frontend when a newer Gruntbooks version is
 * available. Consumers subscribe to the `update:available` topic once
 * at boot; the service debounces re-emits so a single version only
 * fires once per process lifetime, regardless of how many poll cycles
 * observe it.
 * 
 * M5 ships tier-1 auto-update: surface availability, link to the
 * release page, and let the user update through their package manager
 * or a manual download. In-app install (Sparkle/Squirrel) is deferred.
 * 
 * The service is desktop-only. The legacy browser path (`gruntbooks
 * open` → Gin) has no equivalent banner.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check performs a single release lookup and returns the result. Safe
 * to call from the frontend (e.g. a "Check for updates" menu item in
 * a future milestone); does not emit the `update:available` event —
 * callers that want the banner behaviour should use RunAutoCheck.
 */
export function Check(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(374472365).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
