// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WatcherService is the Wails IPC wrapper around the file-change
 * notifications the legacy /api/watch SSE endpoint emitted.
 * 
 * Each StartWatch returns a watchID the frontend subscribes to for
 * two topics:
 * 
 *   - `watch:<watchID>:change` — raw file-change events for the
 *     resolved gruntbook file. Used by author-mode auto-reload
 *     (today's `gruntbooks watch` behaviour).
 *   - `watch:<watchID>:drift` — classified drift events vs. the
 *     snapshot captured at StartWatch time. Consumer-mode shows a
 *     non-blocking banner on these so reviewers notice scripts
 *     changing out from under them.
 * 
 * Stop / Cancel are idempotent so frontend unmount handlers don't have
 * to track whether StartWatch succeeded.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ResetSnapshot re-walks the gruntbook tree and replaces the baseline
 * for an active watch. The frontend calls this after the user clicks
 * "Reload" on the drift banner so a subsequent edit is measured against
 * the just-reloaded state rather than the original open. Returns nil
 * on unknown IDs (the watch already stopped).
 */
export function ResetSnapshot(req: $models.WatchResetRequest): $CancellablePromise<void> {
    return $Call.ByID(1049402323, req);
}

/**
 * StartWatch begins watching a gruntbook for changes. Captures an
 * initial snapshot of the whole tree (excluding .git/node_modules/
 * and the optional output path) and recursively adds every
 * subdirectory to the fsnotify watcher so edits anywhere in the
 * gruntbook produce drift events. The caller MUST eventually call
 * Stop(watchID) to release the fsnotify watcher.
 */
export function StartWatch(req: $models.WatchStartRequest): $CancellablePromise<$models.WatchStartResult | null> {
    return $Call.ByID(2664760995, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Stop cancels an in-flight watcher. Idempotent no-op on unknown IDs so
 * frontend unmount handlers don't have to track whether Start succeeded.
 */
export function Stop(watchID: string): $CancellablePromise<void> {
    return $Call.ByID(837006524, watchID);
}

// Private type creation functions
const $$createType0 = $models.WatchStartResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
