// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WatcherService is the Wails IPC wrapper around the file-change
 * notifications the legacy /api/watch SSE endpoint emitted.
 * 
 * Each Start returns a watchID the frontend subscribes to for
 * `watch:<watchID>:change` events. The payload is a single flat shape
 * (`{path, op, at}`) — richer than the SSE version's bare "reload"
 * string so author-mode UIs can distinguish script edits from
 * gruntbook.mdx edits without re-parsing. Stop cancels the watcher;
 * Cancel is idempotent so unmount handlers don't have to track state.
 * 
 * M5's drift detection (snapshot + classify) will layer on top by
 * subscribing to these change events and publishing `watch:<watchID>:drift`
 * alongside them. For now this service emits raw file changes only.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * StartWatch begins watching a gruntbook file for changes. Returns a
 * watchID the frontend can subscribe to; the caller MUST eventually
 * call Stop(watchID) to release the fsnotify watcher.
 */
export function StartWatch(req: $models.WatchStartRequest): $CancellablePromise<$models.WatchStartResult | null> {
    return $Call.ByID(2664760995, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Stop cancels an in-flight watcher. Idempotent no-op on unknown IDs so
 * frontend unmount handlers don't have to track whether Start succeeded.
 */
export function Stop(watchID: string): $CancellablePromise<void> {
    return $Call.ByID(837006524, watchID);
}

// Private type creation functions
const $$createType0 = $models.WatchStartResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
