// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WelcomeService exposes the Welcome-screen actions (pick folder, open
 * local, list recent) to the frontend over Wails IPC. All methods are
 * safe for concurrent use.
 * 
 * The service also holds the cross-cutting state the frontend needs on
 * boot: whether a gruntbook was passed on the CLI, and whether the
 * backend is running yet. That keeps the frontend from having to poll
 * Gin's /api/health or guess about session readiness.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseCurrent stops the running backend server so the user can return
 * to the Welcome screen and open a different gruntbook in the same
 * session. A no-op if no server is running.
 */
export function CloseCurrent(): $CancellablePromise<void> {
    return $Call.ByID(905616297);
}

/**
 * HandleSecondInstance is the Wails OnSecondInstanceLaunch callback.
 * M2 policy: ignore the second invocation's args (we can't swap out a
 * running Gin server) and bring the existing window forward. Exported
 * so desktop.Run can wire it directly into SingleInstanceOptions.
 */
export function HandleSecondInstance(data: application$0.SecondInstanceData): $CancellablePromise<void> {
    return $Call.ByID(3674843973, data);
}

/**
 * ListRecent returns the recent-gruntbooks list, most-recent-first.
 * Entries whose path no longer exists on disk are still returned — the
 * UI is responsible for showing a "missing" indicator so the user can
 * prune stale entries themselves (they may have unmounted a volume).
 */
export function ListRecent(): $CancellablePromise<$models.RecentEntry[]> {
    return $Call.ByID(1762375179).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenLocal validates a local path as a gruntbook, records it in the
 * recent list, and starts the backend HTTP server for it. Safe to call
 * at most once per desktop-app lifetime — calling twice with different
 * paths returns an error. This matches M2's single-view, single-
 * gruntbook model.
 */
export function OpenLocal(path: string): $CancellablePromise<$models.OpenResult | null> {
    return $Call.ByID(7818747, path).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PickLocalFolder opens a native folder-picker and returns the selected
 * absolute path, or an empty string if the user cancelled. Must run on
 * the main thread — Wails handles that internally when invoked over
 * IPC, but calling it from Go code should go through app.Dialog.
 */
export function PickLocalFolder(): $CancellablePromise<string> {
    return $Call.ByID(2785836176);
}

/**
 * Status returns the frontend's initial boot snapshot. Invariant: if
 * GruntbookOpen is true, ServerPort is > 0.
 */
export function Status(): $CancellablePromise<$models.DesktopStatus> {
    return $Call.ByID(2004347322).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RecentEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.OpenResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.DesktopStatus.createFrom;
