// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService exposes workspace introspection + worktree
 * registration to the frontend over Wails IPC. Read-only methods
 * (Tree, Dirs, File, Changes) are session-agnostic and take only a
 * path; mutating methods (Register, SetActive) require a session
 * token so they match the HTTP path's SessionAuthMiddleware
 * semantics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

/**
 * Changes returns git change metadata for a worktree. Pass a
 * non-empty singleFile to get only that file's diff; pass "" for the
 * bulk changeset. Exceeds maxChangedFiles → TooManyChanges flag.
 */
export function Changes(absPath: string, singleFile: string): $CancellablePromise<api$0.WorkspaceChangesResponse | null> {
    return $Call.ByID(515660206, absPath, singleFile).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Dirs returns the immediate, non-hidden subdirectory names of an
 * absolute path. Used by the DirPicker cascading dropdown.
 */
export function Dirs(absPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(3775430673, absPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * File returns the contents of a single workspace file (absolute
 * path), with metadata flags for images/binaries/oversize files.
 */
export function File(absPath: string): $CancellablePromise<api$0.WorkspaceFileResponse | null> {
    return $Call.ByID(1299981007, absPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Register adds a worktree path to the session's registered worktree
 * list. Matches POST /api/workspace/register — used by
 * GitWorkTreeContext when a clone completes or a worktree is discovered
 * on session bootstrap.
 */
export function Register(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1188286724, sessionID, path);
}

/**
 * SetActive sets the explicitly selected active worktree path.
 * Matches POST /api/workspace/set-active — used when the user
 * switches worktrees in the UI so that target="worktree" templates
 * and REPO_FILES resolve against the selected repo.
 */
export function SetActive(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1521614913, sessionID, path);
}

/**
 * Tree returns the structure-only file tree (plus git metadata) for
 * an absolute workspace path. Callers must pass an absolute path —
 * frontend worktrees always have localPath populated.
 */
export function Tree(absPath: string): $CancellablePromise<api$0.WorkspaceTreeResponse | null> {
    return $Call.ByID(116777217, absPath).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.WorkspaceChangesResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = api$0.WorkspaceFileResponse.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = api$0.WorkspaceTreeResponse.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
